# Chapter 2:  
## Exploratory Experiment 1
## Experiment 1 Review
Spitefulness or spiteful behavior is another aspect of an individual committing a wrong against another person or person. Spitefulness or spite was originally defined as, “behaviors that have negative consequences for both the actor and the recipient” by evolutionary biologists in research in the animal kingdom [@marcus2014] . Psychoanalysts would soon define spitefulness as, “instances in which people harm themselves to punish another…” [@critchfield2008]. Investigations into the origins of spiteful behaviors have been varied: evolutionary psychological, behavior economic, and parental attachment [citations]. Spiteful behavior would be a problematic behavior that in theory should not subsist through consecutive generations. However, spite is seen throughout the animal kingdom. From the bacteria to birds and humans, with obvious variations [citations].  Hamilton’s seminal paper on altruism in the animal was soon changed by research on spiteful behaviors [-@hamilton1970]. Hamiltonian spite articulates the continued existence of spite in spite of the ultimate cost in that it is genetically advantageous and more common for there to be spiteful behavior towards the least similar of peers than the average relatedness to the group. In this sense, spite continues to exist, according to Hamiltonian spite, because the choice of the least similar amongst the average ultimately increases adaptivity. Interestingly, Hamilton contended that if the cost to the individual is less than both or either the benefit or the genetic relatedness than altruistic behavior is favored [@gardner2004; @hamilton1970]. Conversely and more important to spitefulness is that spitefulness may be favored if there is enough negative relatedness between the two individuals (originally hypothesized in relation to animals). 

Spitefulness is also often misconstrued with selfishness [@smead2013]. The difference is the cost applied to the individual. To demonstrate the differences, Alex and Cody are driving down the highway. Alex drives in front and cuts off Cody from their mutual exit. There is no cost applied to Alex when cutting off Cody. However, if Alex was in front of Cody and pushed on the brakes to stop Cody from getting too close and tailgating, then both cars are damaged. In the latter, Alex damages both cars therefore inflicting damage on themselves, which exemplifies a spiteful act.

Researchers further parse spitefulness into either genetic or psychological spite. Genetic spite would be the explanation of the spiteful behaviors based on the genetic relatedness, the aforementioned, while psychological spite is a risky behavior where the organism is required to perform a cost benefit analysis along with analyzing possible futures [@hauser2009]. Note: for brevity, future discussions of spite for humans will be exclusive to psychological spite.

Early examples of genetic spitefulness were demonstrated in bacteria where a bacterium will burst spreading bacteriocins, antibacterial toxins, killing the competitor bacteria [@gardner2006]. In more complex life, some male birds kill the young conspecific chicks without eating them [@barnett2013]. It would not be advantageous for the species if the amount of young were significantly reduced, which then would reduce the fitness of the male bird. Similar yet not as drastic spiteful behavior has been seen in humans. Common examples are in ultimatum games where participants are asked to distribute funds to other participants. Participants that believed that the funds were being unequally distributed out, they would reject the offer [@marcus2014].

Outside of behavioral economics, spitefulness has been seen when people will intentionally take longer in checkout if they are annoyed by the person behind them or taking longer on an exam if the person is in some way annoyed by the instructor. Spite has also been seen in preschoolers in experiments like the ultimatum game with adults [@bauer2014]. In similar research children preschool children half of the time would reduce the amount of payoff of another child even when there would be no reduction in their winnings [@bugelmayer2014]. On average, boys tended to choose the more spiteful choice over the non-spiteful, girls did not show a significant propensity for spiteful behavior. This propensity continues where younger men tend to score the highest on spitefulness than their peers [@marcus2014]. As people age, they tend to be less spiteful and egalitarian and altruistic behaviors increase [@bugelmayer2014]. Spiteful behavior may persist into early and late adulthood.  
The evolution of spite in humans continues to be researched but another research finding points to parenting style. Parenting style includes parental warmth, positive affect, and control [@carlo2011; citations]. Research investigating positive parental connections has shown to predict future secure attachments in relationships and helps foster multiple types of prosocial behaviors and a general emotional sensitivity [citations]. Conversely, a negative parenting style evidenced by low parental warmth and more strict control over the child predicts more anti-social behaviors and future insecure attachments [citations]. Both paternal and maternal warmth was predictive of future prosocial behaviors however, maternal warmth was more predictive than paternal warmth. When there are negative parental attachments, negative traits are predicted to occur. For example, dark personality traits are more likely. These dark personalities were originally a triad of psychopathy, narcissism, and Machiavellianism [citations]. Eventually the triad expanded to include both sadism and spitefulness [citation]. Likelihood for spitefulness to subsist later into life is also reflected by the education level of the parents, where children of less-educated parents tended to be more selfish, less altruistic, and express a weak form of spitefulness [@bauer2014]. Lower socioeconomic status has also been associated with deficiencies in cooperating behaviors that reduce the likelihood of darker personality traits like spitefulness. However, Bauer and colleagues suggest that it may be the circumstances of having a lower economic status that makes it more difficult to form altruistic behaviors in that there are other factors for them to think of. Still, spiteful behavior remains a factor for children in families with low socioeconomic status.

Some adults have a comorbidity with spitefulness and other aggressive personality traits. Investigations of violent offenders have shown interesting effects of spitefulness amongst the other darker characteristics [@rogier2019]. Violent offenders compared to their non-incarcerated controls, displayed increased aggression, narcissism, and spitefulness. Individuals that displayed increased spiteful behavior was due to the need to punish others through externals means without internal control of their behaviors. The spitefulness displayed by the violent offenders also saw an association with difficulty in emotional dysregulation [Citations]. Emotional dysregulation is when an individual has difficulty in either regulating their emotion responses and/or emotional miss regulation where the individual is using the incorrect regulatory strategy in response to the current situation [Gross & Jazaieri, 2014]. In studies investigating the individuals showing instances of spiteful behavior, they may have difficulty in controlling their emotions along with using the incorrect regulatory strategy. Spiteful individuals not only have issues in regulating their emotions, they also have difficulty in recognizing and attributing the emotions of others often misconstruing the causes of the emotions. Furthermore, the spiteful individuals have difficulty with impulse control and coupled with their misconstruing of the emotions of others they may harm the other individual(s) and in turn themselves. Coupled with difficulties in emotion detection, they display increased levels of detachment which may explain their willingness to harm others [@zeiglerhill2015]. These spiteful individuals also have issues with future prospection, which is the ability to judge the consequences of their behaviors and project them into the future [citations]. In doing so they may show irrational behaviors towards themselves and thus harming themselves, the central precept in spitefulness.  
There are several problematic behaviors that become prevalent with individuals that show spitefulness [citations]. Given the readily available high-speed internet, many behaviors are becoming fueled by increased internet use [citations). In some cases, the internet use may become problematic and affect the individual negatively. Kicaburun and Griffiths carried out a series of studies investigating the association between the dark traits or personalities and problematic internet use. Of note, each of the dark quintet traits are associated with problematic internet use. Specifically, Machiavellianism is directly associated with online gambling and online gaming. Spitefulness interestingly was directly associated with internet gaming use and indirectly with online shopping [@kircaburun2018]. Enviousness and feelings of entitlement are leading motivations of spiteful behavior [@marcus2014]. Consequently, individuals high in spitefulness also tend to be higher in both narcissism and low self-esteem which worsens the problematic internet use. Another problematic behavior, which may be facilitated by increased internet use, is not physical spiteful behavior. Research in humor styles has shown two variations, either injurious or benign [@vrabel2017]. Injurious as the name suggests uses humor that is aggressive that belittles themselves and others. Conversely, benign humor is more affiliative and enhances feelings of the self and others. With the increased internet use by individuals that score higher in spitefulness it stands to reason that these individuals would use the internet to further their use of belittling humor styles to harm others possibly expanding their pool of eventual targets.


## Methodology
####	Methods
Participants: Participants were a convenience sample of 82 (Mage = 25.6, SD = 7.54) individuals from Prolific Academic crowdsourcing platform (“www.prolific.co”). Requirements for participation were: (1) be 18 years of age or older and (2) and as part of Prolific Academics policy, have a prolific rating of 90 or above. Participants received £4 or £8 an hour as compensation for completing the survey. The University of Edinburgh’s Research Ethics Committee approved all study procedures (approval reference number: 330-1920/1).

####	Materials:
_Demographic Questionnaire_: Prior to the psychometric scales, participants are asked to share their demographic characteristics.

_Spitefulness Scale_: The Spitefulness scale [@marcus2014] is a measure with seventeen one sentence vignettes to assess the spitefulness of participants. The original spitefulness scale has 31-items. In the original Marcus and colleagues’ paper, fifteen were removed. For the present study however, 4-items were removed because they did not meet the parameters for the study i.e., needed to be dyadic, more personal. Three reverse scored items from the original thirty-one were added after meeting the requirements. Example questions included, "It might be worth risking my reputation in order to spread gossip about someone I did not like." and "Part of me enjoys seeing the people I do not like fail even if their failure hurts me in some way." Items are scored on a 5-point scale ranging from 1 (“Strongly disagree”) to 5 (“Strongly agree”). Higher spitefulness scores represent higher acceptance of spiteful attitudes.

_Sexuality Self-Esteem Subscale_: The Sexuality Self-Esteem subscale (SSES; @snell1989) is a subset of the Sexuality scale that measures the overall self-esteem of participants. Due to the nature of the study, the sexuality subscale was chosen from the overall 30-item scale. The 10-items chosen reflected questions on the sexual esteem of participants on a 5-point scale of +2 (Agree) and -2 (Disagree). For ease of online use the scale was changed to 1 (“Disagree”) and 5 (“Agree”), data analysis will follow the sexuality scale scoring procedure. Example questions are, “I am a good sexual partner,” and “I sometimes have doubts about my sexual competence.” Higher scores indicate a higher acceptance of high self-esteem statements.

_Sexual Jealousy Subscale_: The Sexual Jealousy subscale [@worley2014] are 3-items from the 12-item Jealousy scale. The overall jealousy scale measures jealousy in friendships ranging from sexual to companionship. The 3-items are “I would worry about my partner being sexually unfaithful to me.”, “I would suspect there is something going on sexually between my partner and their friend.”, and “I would suspect sexual attraction between my partner and their friend.” The items are scored on a 5-point scale ranging from 1 (“Strongly disagree”) to 5 (“Strongly agree”). Higher scores indicate a tendency to be more sexually jealous.

_Sexual Relationship Power Scale_: The Sexual Relationship Power Scale (SRPS; @pulerwitz2000) is a 23-item scale that measures the overall power distribution in a sexually active relationship. The SRPS is split into the Relationship Control Factor/Subscale (RCF) and the Decision-Making Dominance Factor/Subscale (DMDF). The RCF measures the relationship between the partners on their agreement with statements such as, “If I asked my partner to use a condom, he [they] would get violent.”, and “I feel trapped or stuck in our relationship.” Items from the RCF are scored on a 4-point scale ranging from 1 (“Strongly agree”) to 4 (“Strongly disagree”). Lower scores indicate an imbalance in the relationship where the participant indicates they believe they have less control in the relationship.

The DMDF measures the dominance level of sexual and social decisions in the relationship. Example questions include, “Who usually has more say about whether you have sex?”, and “Who usually has more say about when you talk about serious things?” Items on the DMDF are scored on a 3-item scale of 1 (“Your Partner”), 2 (“Both of You Equally”), and 3 (“You”). Higher scores indicate more dominance by the participant in the relationship.
    
_Scenario Realism Question_: Following Worley and Samp in their 2014 paper on using vignettes/scenarios in psychological studies, a question asking the participant how realistic or how much they can visualize the scenario is. The 1-item question is “This type of situation is realistic.” The item is scored on a 5-point scale of the participants agreement with the above statement, 1 (“Strongly agree”) to 5 (“Strongly disagree”). Higher scores indicate disagreement with the statement and reflects the belief that the scenario is not realistic.
    
_Spiteful Vignettes_: After participants complete the above scales, they are presented with 10-hypothetical vignettes. Each vignette was written to reflect a dyadic or triadic relationship with androgynous names to control for gender. Five vignettes have a sexual component while five are sexually neutral. An example vignette is, 
	“Casey and Cole have been dating for 6 years. A year ago, they both moved into a new flat together just outside of the city. Casey had an affair with Cole's best-friend. Casey had recently found out that they had an STI that they had gotten from Cole's best-friend. Casey and Cole had sex and later Cole found out they had an STI.”
For each vignette, the participant is asked to rate each vignette on how justified they believe the primary individual, Casey in the above, is with their spiteful reaction. Scoring ranges from 1 (“Not justified at all”) to 5 (“Being very justified”). Higher scores overall indicate higher agreement with spiteful behaviors.
## Procedure: 
Participants were recruited on Prolific Academic. Participants must be 18-years of age or older, restriction by study design and Prolific Academic’s user policy. The published study is titled, “Moral Choice and Behavior.” The study description follows the participant information sheet including participant compensation. Participants were asked to accept their participation in the study. Participants were then automatically sent to the main survey (Qualtrics, Inc.).

Once participants accessed the main survey, they were presented with the consent form for which to accept they responded with selecting “Yes.”. Participants were then asked to provide demographic characteristics such as gender, ethnicity, and educational attainment. Participants would then complete in order, the spitefulness scale, the sexual relationship power scale, the sexual jealousy subscale, and sexuality self-esteem subscale. Next, participants were presented ten vignettes where they were instructed to rate on the level of justification for the action conducted in the vignette. After each vignette, participants would rate the realism of the scenario. Upon completion of the survey (median completion time 17 minutes and 5 seconds), participants were shown a debriefing message and contact information of the Primary Investigator (Andrew Ithurburn). Participants were then compensated at £8/hr. via Prolific Academic.

####	 Data Analysis: 
Demographic characteristics were analyzed using a one-way analysis for continuous variables (age) and Chi-squares tests for categorical variables (sex, ethnicity, ethnic origin, and educational attainment). Means and standard deviations were calculated for the surveys along with correlational analyses (e.g., spitefulness, SESS, SRPS, SJS). Bayesian multilevel models were used to test differences between levels of justifications of vignettes that are either sexually or non-sexually vindictive in behavior. Model 1 
## Results:
Table # presents the results of the multilevel model of the present study. Ninety-seven individuals attempted to participate in the study, 15 of these individuals opted to return the study and discontinue participation. A majority of the participants identified as male (n = 50) while 30 identified as female and 2 as gender non-binary. There was a moderate skewness towards the right in age (1.40). Table # shows the demographic information for study 1. A Spearman correlation was conducted on the four psychometric tests along with the age of the participants. The sexual jealousy subscale (SJS) and the sexual relationship power scale (SRPS) resulted in the only significant correlation r = -0.55, p < 0.0001.
### Spitefulness: 
Justification as a function of the four indices was not entirely explained by the proposed model. The posterior mode for the fixed effect of Spite $\gamma$ = 0.02. 95% CI [0.01-0.03], indicating that there was an insignificant difference between the levels of spite and justification of vindictive behaviors. When looking at percentage change of behavior given the $\gamma$, around 2%.
The mode of the posterior distribution for the variance among the random effects for the justification of the vignettes was $\alpha$<sup>2</sup> = 1.07, 95% CI [0.98 – 1.09] indicating that there was variation amongst the participants in their justification of the vignettes.


##  Discussion:

\newpage