---
title             : "The psychology of risk and power: Power desires and sexual choices."
shorttitle        : "DoPL and DOSPERT"

author: 
  - name          : "Ithurburn, Andrew"
    affiliation   : "1"
    corresponding : yes    # Define only8 one corresponding author
    address       : "7 George Square, Edinburgh, EH8 9JZ"
    email         : "a.ithurburn@sms.ed.ac.uk"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)

affiliation:
  - id            : "1"
    institution   : "The University of Edinburgh"
  

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.
 

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         :  "2004"

bibliography      : ["references.json"]

floatsintext      : yes
numbersections    : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no
mainfont          : "Times New Roman"
geometry          :  a4paper, left = 4cm, right = 2.5cm, top = 2cm, bottom = 4cm
always_allow_html: true
header-includes:
  - \pagestyle{plain}
  - \setcounter{tocdepth}{5}
  - \linespread{1.2} 
  - \usepackage{setspace} 
  - \shorttitle{}
  - \rhead{DoPL and DOSPERT}
  - \usepackage{fancyhdr}
  - \cfoot{\thepage}
  - \fancyheadoffset[L]{0pt}  
  - \fancyhf{}
  - \fancyhead[RO,LE]{\small\thepage} 
  - \renewcommand{\headrulewidth}{0pt}
  - \interfootnotelinepenalty=10000
  - \usepackage{setspace}
  - \newcommand{\HRule}{\rule{\linewidth}{0.25mm}}
  - \let\cleardoublepage=\clearpage
  - \usepackage{atbegshi}% http://ctan.org/pkg/atbegshi
  - \AtBeginDocument{\AtBeginShipoutNext{\AtBeginShipoutDiscard}}
  
 
documentclass     : "apa7"
csl               : "apa7.csl"
class             : doc, 12pt, a4paper
classoption       : "donotrepeattitle"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
source("libraries.R")

```
```{r child = "front.Rmd"}

```

\newpage

\tableofcontents

\newpage


```{r child = "Introduction.Rmd"}
```

```{r child = "Chapter2.Rmd"}
```



\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup

\newpage