---
bibliography : ["references.json"]
---
# Chapter 1:  
## Literature Review
### General Introduction
Research in decision-making is not only concerned with understanding monumental decisions done in a study or saving a life, but equally in more mundane decisions such as understanding choosing what tea to drink in the morning, what clothes to wear that day or whether a couple should have a divorce. Making models of decisions can be difficult given uncertainty is involved along with risk [citation]. For example, two adult men [or a man and a woman] that are intending to have sex need to make the decision of whether or not to use a condom. Added uncertainty is involved with the decision-making process. One partner may have multiple sexual partners while the other may have only had one, one partner may have a sexually transmitted infection and might not feel the need or feel comfortable with informing their partner of their status. Consequences of not informing can have dire consequences on both partners. 

In 2016, the year of most recent global  data collection, there were 376 million necases of the four curable sexually transmitted infections, chlamydia, gonorrheatrichomoniasis, and syphilis [@worldhealthorganization2018]. The World HealtOrganization [WHO] further estimates that there are one million new cases of a curablsexually transmitted infection each day. Due to multiple factors, certain minoritpopulations are more at risk for contracting new sexually transmitted infections, e., men who have sex with men and female sex workers [@worldhealthorganization2018].  Some factors includcertain societal beliefs men who have sex with men might engage in nonrelational sex “just trying to figure things out…it’s just a hook up phase” [@elder2015a] , ambiguous laws concerning the legality of sex work interfering witsafe and available locations for such activity, as well as. There may alsbe some difficulties in their willingness in their activities be it forced by anotheor sheer necessity. For countries like Scotland there have been a reduction ithe amount of new cases of STIs like HIV amongst key populations, however new risks oantibiotic resistant gonorrhea, _Neisseria gonorrhoaeae_, have shown a new prevalence in many countries [@ison2011].

### Who is at risk?
There is then the arduous task of how to research the topic of sexually transmitted infections and methods of then understanding what is occurring in the individual. There are neurobiological explanations such as certain brain formations occurring that cause individuals to have difficulty understanding the consequences of their actions [@moll2005; @schaichborg2008; @tsoi2018]. There are also more cognitive explanations as well that have shown promising results. For example in the cognitive sub-area of metacognition there is an understanding that there are certain cognitive mechanisms that aid in the individuals ability to regulate their own cognitive understanding of their decisions [@anderson2002; @yeung2012]. This self-regulation then contributes to their ability to control whether they act on their baser needs or are able to understand the consequences of what they might or might not engage in [@crandall2017; @anderson2002]. How individuals had reached the information on the effectiveness of certain behavioral changes that reduce the chances of contracting an STI is also in question. For example, research shows that individuals that have a greater understanding of the impact and chances of contracting HIV, actually engage in risky sexual behaviors and therefore increase their chances of contracting the very infection they have more knowledge [@kirby2007]. Skills based training showed more positive results on practicing safer sex practices. How an individual sees themselves as either a sexual person or person in general is also a factor in how they later may meet an STI  [@gesink2016; @andersen1994; @andersen1999; @elder2015a]. Aggression, in the cognitive sense, also has an impact as well demonstrating a dominance over another person that may cause difficulties in their own ability to make decisions on their sexual health [@malamuth1996; @williams2017].

Aggression is one method of exerting control over another individual. Overall, the exertion of control itself denotes a power disparity between parties which varies in effects, methods, and domains. [citation]. For example, most research has looked at power-over or one person controlling the behavior of another person. This area of research connects the cognitive explanation to behavioral outcomes. Research in power also includes looking at minority populations and aspects of power over to help explain the increased prevalence of certain STIs by discussing and researching certain power dynamics [citations]. The institutional support of those power dynamics often reflect power based on age, gender, political orientation, sexual orientation and gender identity [@anderson2002; @volpe2013; @winter1988; @chiappori2019]. Investigations of the power structure of a family unit has shown to have some interesting consequences on sexual health depending on the type of parenting style and parental attachment [@bugental2002; @chiappori2019; @kim2020; citations]. A new area of research coming out of power and cognition is the phenomenon where an individual will harm themselves in some way to also inflict harm on another. This type of behavior has been researched extensively in the animal kingdom and is known as spiteful behavior in that one brings down their own wellbeing to spite the other person. There would be interesting avenues to research how spiteful thinking may affect an individual in how they choose one course of action over another.
### Current Methodology
An interesting aspect of the power dynamics and cognition is the moral aspect of decision-making. Often, sexually transmitted infections and risky sexual behavior are used as examples to discuss moral issues. Methods at understanding these situations and other moral issues are through dilemmas or vignettes where individuals are presented with a short scenario and given the opportunity to choose one outcome over another [@ellemers2019]. A trademark example is the trolley car experiment where there is a runaway trolley car that is going towards five people [@greene2001]. The decision is thus, allow the trolley to careen towards the five people or you could divert the trolley by pushing and sacrificing a large man for the sake of the other five. This type of dilemma poses an interesting method of understanding how and what the decision maker would choose. The researcher can then change the dilemma on its severity and complexity. There could also be a change in situation and the types of individuals that are at risk. Individual choice tasks investigating risky sexual behaviors and STIs could be furthered with investigating the moral decision-making aspect of those issues.
Current STI research has focused on methods of ways of curbing why individuals act a certain way when presented with a risky sexual situation [@kirby2007]. Current methods have shown mixed results. In many countries, how people are taught about risk and sex can vary wildly [@unesco2015]. For example, some countries may have one standard that is a mix of religious and scientific findings of STIs. While others may not even have a formal sexual education program. Some aspects of sexual activity are not even discussed, for example non-heterosexual sex is not always present in education [@ellis2004]. This becomes problematic in that men who have sex with men tend to be more at risk to contracting an STI than their peers who engage in heterosexual intercourse. There has also been a lot of research in STI rates. Evidence by governments and international health organizations constantly partnering with universities and healthcare providers to collect new incidences of STIs. There might be one way of researching the topic however, it might not look at all the aspects. Some may be more focused on the outcome while ignoring the causes or hypothesized causes of the outcome. Continued research into the understanding of decision-making is important in that understanding the general helps later understanding of the specific.

## Risky Sexual Behaviors and STIs
Sexual activity/ability to reproduce being one of the seven characteristics of life can cause health, financial, and/or social dangers (to all participants) through risk and neglect [citation]. The curability or manageability also plays a factor in how an STI will affect an individual or community. For example, if the treatment is simple and cheap the effect could be minimal. However, if the treatment cost is expensive the drain on multiple resources could be detrimental.

There is a large array of different sexually transmitted infections. Currently, there are eight common types of STIs, chlamydia, gonorrhea, trichomoniasis, genital warts, genital herpes, pubic lice, scabies, and syphilis [@carmonagutierrez2016], chlamydia being the most common. Treatment for these STIs can range from a simple course of antibiotics such as is the case with chlamydia or gonorrhea. Conversely, treatment for syphilis or human immunodeficiency virus [HIV], can be increasingly more involved, cause difficulty in daily life, and have higher costs [citation]. Globally, 37.9 million people are living with HIV [104,000 in the United Kingdom], with 1.7 million being under the age of 15 years old [@ison2011]. The treatment for HIV currently is through antiretroviral medication, which is often a combination of multiple medications to account for the high adaptability of the virus [@costalourenco2017].

New difficulties appear from the most common treatment strategies. The main strategy being through targeted and high doses of antibiotics. Concern arises given the fluctuating nature of STI treatment and costs. As such, costs for treatments have seen a markable increase with some treatments costing [enter average amount]. An increasing number of antibiotic resistant gonorrhea is occurring globally, with a recent discovery in Japan with a strain that is resistant to ceftriaxone, the most prescribed antibiotic [citations]. Two individuals in the United Kingdom recently [2019] separately tested positive with different strains resistant to not just ceftriaxone but also azithromycin [citations]. The confirmed cases may seem small however, 10% of men and half of women do not show visible symptoms when infected with the bacteria. Medical treatment alone has not been the only strides made in STIs around the with strides in acceptances and less persecution for those that have HIV for example. However, while persecution and stereotyping has gone down in recent years, treatments and availability to those treatments have become increasingly more costly.  
Sexually active individuals can become infected with an STI through various forms. The first and most prominent vector is through risky sexual behaviors, i.e., multiple sexual partners, unknown sexual history of partners/high-risk individuals, and unprotected sex [citations]. The most common vector is through engaging in unprotected sex. Condoms are the most common and effective method of protection, with spermicides increasing their effectiveness [citation]. Once infected, the STIs may have detrimental health effects. For example, genital herpes may cause infertility in women and certain types of cancers [citations]. Infections can also be transmitted to infants during childbirth. If left untreated death is possible for example in the case of syphilis which results in an agonizing death [citations]. Condoms are still one of the most effective strategies to practice safe sex along with asking partners about their sexual histories.

Even though condoms are the most effective prophylactic, there is still a chance that an individual may contract an STI. Other risky sexual behaviors can increase an individual’s susceptibility such as having multiple sexual partners. The age of first sexual intercourse is one of the leading factors that has been associated with increased sexual risk taking and later transmission of STI [@tuoyire2018; @desanjose2008; @dickson1998]. Dickson and colleagues investigated the age at first sexual intercourse and found that women that had their first sexual intercourse before 16 years-old were more likely to report having contracted an STI. In the United Kingdom, age at first heterosexual intercourse has decreased over the last 70 years [@mercer2013]. Mercer and colleagues conducted a longitudinal analysis of age at first sexual intercourse by separating individuals into birth cohorts. Individuals age 65-74 years reported their age at first heterosexual intercourse at 18 years. Every ten years that number has steadily decreased by one with the most recent being 16 years old. Thirty percent of individuals between the ages of 16-24 report have had heterosexual intercourse before the age of sixteen.

Individuals 18-24 years of age are not just having intercourse at earlier ages, they are the group with the highest susceptibility of contracting an STI, amounting for #### of new incidences [citation]. College students/aged individuals have also increased alcohol consumption which contributes to lowered inhibitions and increased risky sexual behavior.  Because many are developing sexually including some living away from home for the first time, they are more likely to engage in sexual experimentation such as multiple sex partners and in some cases may not use protection such as a condom.
Lack of communication has also been shown to influence the likeliness of contracting an STI. Desiderato and Crawford investigated risky sexual behaviors in college students and found that failing to report the number of previous sexual partners and their STI status was common in both men and women [-@desiderato1995]. The social stigma of having contracted or being suspected of contracting an STI is one of the most common barriers that inhibits open communication between sexually active individuals [@cunningham2009]. Stigma concerning a positive STI diagnosis can affect not just the physical health of an individual but the psychological health as well. In a series of five experiments, Young and colleagues investigated how the belief of having an STI has an individual's likelihood of getting tested/treatment [-@young2007]. They discovered two key points on stigma, others perceive those that have an STI as being less moral and others believe that others will see them as being immoral. This threat of appearing to be immoral may cause the individual to feel as though the mere perception of having an STI is shameful [@cunningham2009].

The social effects of sexuality in general influence how people see themselves. For gay men in particular there is not just the social stigma that some may have of homosexuality, within the gay community there are some that are expected to be promiscuous or appear to be promiscuous [@elder2015a]. In a study based on grounded theory, Elder and colleagues asked gay men all aspects of sexuality to discover and investigate their sexual schemas. A sexual schema is, “a generalization about the sexual aspects of oneself.” [@elder2015a, pg. 943]. The effects of negative sexual self-schema are also seen in bisexual and straight men and women [@elder2015a; @elder2012; @andersen1994; @cyranowski1999]. Having poor sexual self-schema can result in women having issues with sexual desire and an inability of reaching orgasm while in men can result in climaxing too early and erectile dysfunction [@kilimnik2018; @cyranowski1999]. Long lasting impairments can often lead to more psychological issues.

Individuals that have contracted an STI are also more likely to be ostracized from their immediate community. For example, gay men who contracted HIV in the beginning of the AIDs crisis were often ostracized by society even when they were seeking treatment in the hospital. Nurses would often, for lack of knowledge of transmission of the virus, would often drop medication in front of the patient's door and would rarely physically interact with them [citations]. This ostracization further compounds the psychological and physical trauma that individuals with HIV already have. As more knowledge of how HIV is transmitted individuals can get more efficient and better treatment. However, ostracization often occurs [citations].

## Moral Judgment and Decision-Making
Sam has frequent and unprotected sex with multiple partners, resulting in a sexually transmitted infection that causes visible sores on the mouth and hands. On the way to the chemist one day, Sam has an acute heart attack. Bystanders rush to help, but see the sores on Sam’s mouth and hands. How would the bystanders react? Would they resuscitate Sam? Would it be morally wrong for them not to risk contracting an unknown disease from Sam, even if it may cost Sam’s life? Similar sorts of dilemmas are often used to study moral decision making of various sorts [citations]. the thought experiment of the trolley dilemma. In research by Haidt and colleagues, compared psychologically normal adults to psychopathic traits and performance on the Moral Foundations Questionnaire [MFQ; @graham2011]. Findings included higher psychopathic tendencies were associated with lower likelihood of following justice based norms, weak relationship with disgust-based and in-group norms, and finally an increased willingness to violate any type of norms for money [Glenn et al., 2008].  The key factor in the Moral Foundations Questionnaire are these moral foundations of which there are five moral domains: harm versus care, fairness versus cheating, loyalty versus betrayal, authority versus subversion, and purity versus degradation [citations]. Each of these moral domains have a good and bad component compared to the action type.

The MFQ has been extensively used in research on moral decision-making, with common subjects being on political thought [citation]. In the early studies of moral foundations theory, Haidt investigated the moral foundational differences between individuals that lean either politically liberal or conservative. Of the five moral domains, differences appeared in the likelihood of how either conservatism or liberalism affects the likelihood of individuals to endorse each domain. For example, liberalism suggests protecting the individual from harm by the society, especially if they are a member of a minority group. Conversely, conservatism, namely religious conservatism suggests a propensity for sanctity and purity, along with respecting authority and following the societal moral codes [citations]. Emotional valence is often the best predictors of moral judgments [citation]. The more emotional valence the faster the response time the decision-maker decides and the more staunchly held they are to their decision. Interestingly, participants would be unable to express or support the decisions that they made. Often, participants would downplay their decisions by laughing or stuttering [@haidt2001]. Additionally, as their emotional valence of the decision is higher, people are consistently holding on to their judgments regardless if they were able to support their judgements when asked or not. It then makes sense why some individuals are more politically intransigent given their deeply held moral codes.

Politically held beliefs are often emotionally laden [@marcus2000]. Accordingly, moral foundations theory postulates that there is a good versus bad in the moral domains. When participants are asked to respond to statements that are only offensive but were not harming anyone, participants had issues supporting whether the statement was good or bad. For example, when participants were given a story of cleaning the toilet with the national flag, participants would respond that it is bad and said that they just knew that it was wrong [citation]. Often when individuals violate the moral rules of “cleaning the toilet with the national flag” violators will be judged as immoral and sometimes punished for their actions [citations].  Intuitively the participants responded that the actions were morally were obviously morally wrong. Requiring little to no explanation as to whAn interesting facet of moral judgment is how individuals react to moral decisions when they are reminded of their own mortality [@rosenblatt1989; @greenberg1990]. Reminding individuals of their mortality causes them, according to terror management theory, to want to push away from the thought of their eventual death. To do this people often cling to their deeply held cultural beliefs to remove their thoughts from reality [@greenberg1990]. In the first of a series of experiments Rosenblatt and colleagues found that participants that were reminded of their mortality judged prostitutes more harshly, more so if the participants already had negative opinions on prostitution. This was also seen conversely with heroes that follow the cultural norms. Those participants advocated for a larger reward for those individuals [@rosenblatt1989]. The already held opinions were further investigated to where Christians were asked to report their impressions of Christian and Jewish individuals after mortality became salient. Those that were a member of the in-group, Christian, were more likely to be regarded as more positive than their out-group counterparts, Jewish individuals [@greenberg1990]. In-group bias is an oft studied concept in psychological research. Mortality salience and moral violations tend to increase the strength of the in-group bias and then moral judgement and condemnation [citation].

When a person does a negative action, the reason for the action is often judged and assumed. An action is commonly seen as being intentional when the individual actively does the action directly. However, intentionality becomes problematic participants have already had negative evaluations of the individual. In an experiment where participants were asked to judge the culpability of an airline passenger that was forced by high-jackers to kill another passenger, the high-jackers were the external force forcing the passenger to commit murder. However, when the participants were told that the passenger already wanted to kill that passenger before the hijacking was occurring, they were judged as more culpable. With or without the internal motivation of wanting to already kill the other passenger, the resulting death still occurs. When participants were given a, less vivid, story of a manager that was only mistreated a black employee and another story of a non-bigoted manager that was mistreating all of their employees, participants judged the bigoted manager more negatively. Even though there were differences in those affected between the managers, participants already held a negative opinion for those that hold bigoted views, and thus judged the bigoted manager more severely [citation].

Research in attributional blame continued with an experiment investigating passengers on a sinking boat [@uhlmann2013]. Participants were given a story where there were several individuals on a sinking lifeboat. There were too many people in the boat and the only course of action given was that some of the passengers had to be thrown overboard. In the utilitarian perspective, used for this example, the morally correct judgment was a few must be sacrificed for the safety of the larger group [citation]. However, the participants often judged the surviving passengers as acting selfishly. Thus, they were seeing the passengers as immoral.

When individuals commit a moral violation, as would be the case for the surviving passengers, it is not only important to investigate how others would judge and react but also how the individual reacts to their own action [@tangney2006]. Emotional reactions occur when someone does a behavioral action, or they expect a behavioral action to follow. An interesting aspect of emotional reactions are emotional reactions tied to moral judgment. When an individual violates a moral norm, they often feel a personal feeling of shame or guilt which are two of the most commonly studied of these self-evaluative emotions [@tangney2006]. There is an inherent difference between these two emotions, shame is inferred as being negative feelings of oneself that has a public display, while guilt is similar sans the public display [@tangney1996]. Individuals who violate the community’s customs on purity often feel a sense of shame. While guilt is commonly felt with a violation of community [citations]. People with STIs are often left feeling shame from their suspected purity violation and thus are often stigmatized for their behavior and punished in some form by the community. This can lead, as discussed in the previous section, to increasing their sense of isolation and negative self-worth. How the moral violators react to their shame or guilt is dependent on whether they experience the former or the latter.
There are often attempts to amend the situation when individuals have violated moral norms. Depending on the self-evaluative emotion that is being felt, people will make amends to try to change the situation or they may hide it [@tangney1996]. Guilt is the former and shame is the latter. In most cases individuals that are feeling shame will attempt to ignore their moral violation where they will deny or evade the situation that is causing them shame. Conversely, people with guilt are often motivated by those negative feelings to fix the situation that caused them to feel the guilt. Guilt is often feeling negativity towards a specific action while feeling ashamed or shame is usually a reflection of the entire self [citations]. Thus, in relation to how to repair the guilt inducing act, it would appear to be more manageable if the inducing situation was a singular event rather than a feeling of the entire self. Participants that were prompted to feel shame were less likely to express empathy for someone with a disability [Marschall, 1998 as cited in @tangney2006]. When people feel a sense of shame, they self-evaluate and reflect on themselves. This hinders the empathy process that would require them to focus their attention on the emotions of another person.

Barnett and Mann investigated sexual offenders to understand how feelings of empathy are blocked for their victim at time of the offense [-@barnett2013]. In empathy research, emotions cannot only just be inferred by the situation but be “felt” to be classified as expressed empathy. Earlier research looking at empathy by sexual offenders has not shown them as being unempathetic. However, Barnett and Mann contend that sexual offenders may have a disruption in seeing distress in their victim. The offender may then believe and assert that their victim deserves the distress that they are experiencing and have a cascading effect where they may be powerful and enjoy the distress of the victim [@barnett2013].

## Power
A common denominator in research on the dark personality and moral judgment is the influence of power. To define power, one would have to first define the actor and the recipient of the power. Therefore, there is either power-over, power-to, and power-with. Each aspect has their own different consequences [citation]. Power-over is when there is one individual, the one with power, which wields control over a subordinate individual [citation]. Power-to is when an individual of privilege uses their status and power to control and enact a certain consequence [citation]. Finally, power-with is an interesting concept where a person of power uses their own power to lift or elevate someone without power to a power position [citation]. This is often seen in community projects where someone in power goes into a troubled community and facilitates the situation so that those that have less power can have their voices be heard. Power also has various sources each with their own complex consequences: institutional, cultural, gender, age, ethnicity, orientation, and gender-identity [citations]. Some sources of power compound on one another to increase the level of power over other singular sources of power. For example, in many areas of the world a straight white cisgender man would hold the most power relative to other individuals.

Power influences relationships be it romantic or familial, work, academics, including each of their derivatives. The three variations of power have various influences on each of the areas of life. Power is neither good nor bad, it is how the power is used that makes it either good or bad [citation]. Power and power structures are often in the media. Often when there is a military coup in a far-off country, individuals discuss power-over. When a humanitarian goes into an impoverished community to help their voices heard, power-with is discussed. As with the previous example, when a legislator uses their influence to pass a law, that legislator uses power-to.

Early discussions of power descended from Greek and Roman political philosophy [@aristotle1984]. Greek Philosopher, Plato’s brothers Glaucon and Adeimantus discuss the viability or requirement of citizens being just and lawful if they are able to escape conviction because of some social power or fortune [@aristotle1984]. Aristotle continued the discussion by posing the questions, “There is also doubt as to what is to be the supreme power in the state: Is it the multitude? Or the wealthy? Or the good?...” [@aristotle1984]. Power discussions such as that by Aristotle point to what is the source of someone’s power. Does the power come from the majority? Does it come from money? Does it come from those that are just? Each source of power has different effects on those that are governed by those with that power. Polybius of Greece discussed how a constitution should be created and power should be delineated. Polybius power should be split between multiple groups, each with a different form of power and distinct genre to wield that power [citation]. Power continued to be discussed well beyond the Greek philosophers and continued by political researchers and philosophers. Discussions of power soon developed into research on how it influences at the community level.

Sociologists, following many of the philosophical thought experiments previous and current to the time, began to research power. Sociologists soon developed the area of research in social power, where political power was a subset. According to Bierstadt, power is always successful, whenever it fails then it is no longer power [1950]. Sociologists asserted that power be conceived of as a force, something that is applied to control a situation. Power can also be conceived of as more passive authority. There are three sources of power: number of people, social organization, and resources. From that individuals that are the class or group or have the most resources that are in need are those that will have the most power.  Resources need not be physical objects they can also be more psychological such as skills or knowledge. From history there are many examples where power becomes toxic and the leader becomes the oppressor. Be it Mao Ze Dong, Stalin, Lenin, or Hitler. The question then becomes what causes the powerful to become oppressors? In some cases, those that are in power are trying to do good for the community, restrictive from the example.

Recently, issues and abuses of power have become much of the forefront of news due to the explosion caused by the me-too movement [citation]. The me-too movement was first coined by activist and sexual harassment survivor Tarana Burke. A decade after she disclosed her sexual assault, the me-too movement and the abuse of power dominated the new cycle with accusations against film producer Harvey Weinstein [citation]. Weinstein was known for doing philanthropic initiatives during his career by using his influence and money to aid the certain initiatives that he had chosen. However, soon news of his sexual assault accusations and threats became news. Soon multiple women came forward accusing Weinstein of assaulting them as well and using his power over them to intimidate and silence them [citation]. This exemplifies how resources and position aid in individuals become powerful. Weinstein had the resources and the authority to abuse his power with many of his peers knowing what he was doing [citation].

In psychology, it was originally conceived that power corrupted individuals exemplified by the Stanford prison experiment where “regular” individuals were instructed to play the prison guards of a simulated prison. Similar individuals were instructed to portray the prisoners [citation]. Zimbardo, the lead researcher for the experiment, soon noted that the individuals that portrayed the prison guards became aggressive with the prisoners. They verbally and physically assault them. The experiment was halted to stop any more damage from occurring. News spread of the results of the experiment and power was seen as causing or influencing the “prison guards” to become aggressive and abuse towards the “prisoners.” However, the nature of the participants became into question [citation]. Later researchers noted that there could have been a self-selection bias of the participants. The experiment was advertised such that the prison experiment was known to the participant. This would then cause individuals to self-select into the group which could possibly skew the results given that the participants may have had authoritarian tendencies and the experiment and added power may have given the opportunity for the participants to express their authoritarian tendencies already present [citation]. Similar explanations have occurred in politics.

Throughout political history individuals that have reached powerful positions on multiple occasions have given some powerful people the outlet to express their prejudiced and problematic beliefs [citation]. Fear of communist infiltration in the United States caused many fears and blacklisting was a frequent practice. Joseph McCarthy, a Wisconsin senator, would soon use his power as a legislator/senator [citation]. McCarthy would call individuals to the front of the House Un-American Activities Committee because they were suspected of being spies for the Soviet Union. McCarthy and the committee used strong arm tactics and would often threaten individuals brought in front of the committee. Many individuals brought forward often had their lives irrevocably changed [citation]. Soon Senator Margaret Chase Smith and six others condemned McCarthy for his actions and tactics. McCarthy was soon censured, and the House Un-American Activities Committee was disbanded. The political issue of power being used as an outlet for prejudiced and authoritarianism became apparent recently after the 2016 United States Presidential Election [citation]. Donald Trump’s political exploits would soon highlight his past and present use of power and his unethical dealings. Often Donald Trump would use his power for personal gain and to express his prejudicial and racist beliefs. Examples range from in the 1990’s Donald Trump advocated for the Central Park Five, five African-American men accused of raping and murdering a young White woman in Central Park, to be put to death [citation]. However, DNA evidence exonerated on the men of the crime [citation]. Recently, Donald Trump on the campaign trail accused Mexico of sending individuals across the border that were rapists and drug dealers. However, there was no physical proof of the case and became a common trope used by Donald Trump supporters. Because of the misuse of power and authority, there have been increased hate crimes towards Mexican Americans and African Americans [citation]. The Southern Poverty Law Center, an organization that records the number of hate groups currently active in the United States has documented a clear increase in the number of active hate groups after the 2016 election [citation]. The supporters feel a sense of validation for their own beliefs and opinions which they feel allows them some power in and of itself. This then poses an interesting question in power research in psychology. What are the correlates of the power complex? What are the consequences of power? How does a power imbalance affect relationships? The list of questions is vast and varied.

Power imbalances in relationships can have negative effects spanning the entirety of an individual’s life, be it emotionally, physically, psychologically, and socially [citation]. Dr. Helene Papanek, director of the Alfred Adler institute, a sub-clinic of the Alfred Adler Mental Hygiene Clinic, discussed at a meeting of the Association of Humanistic Psychology, multiple cases of controlling and power disturbances in personal relationships. A relational example was presented where a father, Mr. A had complete control over his wife and daughter. Controlling when they should be home and where they should go. Mr. A even controlled the frequency and positions of sex [@papanek1972]. Power-over someone can also manifest feelings of low self-worth and destructive behaviors. For example, Ms. C was a young mother of a child born out of wedlock. She was abandoned by her parents and the father of her child. She was constantly controlled by her mother and their disdain for her child out of wedlock. Soon she developed panic attacks but also a sense of superiority over others as a defense mechanism. Dr. Papanek noted that Ms. C developed and lived a life of spiteful behaviors one after the other.

The behaviors of Ms. C and Mr. A are not the only examples of individuals having power over another person or being subjected to the power over them. Power-over has occurred throughout human history and is ingrained in all cultures [citation]. Institutional power-over is quite common cross-culturally. Contraception and control over one’s own reproductive system is a prescient debate globally [citation]. In 1960 and 1963 Enovid was approved for use in the United States and United Kingdom respectively [citation]. Doses for contraception early on were often high and news of multiple deaths was reported widely. Cases were brought forward to control the use of contraception. The Roman Catholic Church’s stance on hormonal contraception shifted from permission to outlawing anything that would be believed as stopping the ability to propagate [citation]. Interestingly in 1989 researchers working for Pfizer in the United Kingdom were researching a new drug that would aid in treating heart conditions [citations]. The researchers soon discovered sildenafil also could treat erectile dysfunction. Ten years later, sildenafil, brand name Viagra, would be patented and approved for use for the primary treatment for erectile dysfunction [citation]. The same individuals that were trying to reduce the use of female contraception were not trying to do the same for Viagra. The Japanese government and officials had similar attempts to quell the use of female contraception while not doing the same for erectile dysfunction treatments [citation].  
The Council on Foreign Relations [CFR] a non-profit that specializes in United States and international affairs, conducts an international  index on women’s workplace equality by rating each country on factors: accessing institutions, getting a job, going to court, protecting women from violence etc. [citation]. Scores range from 0 to 100 where 100 is near total equality in all areas. Of 189 countries on the list only 9 score over 90% in the ranking. One hundred and thirty-eight score below 75 with Yemen having the lowest score of 24.5. Including those that intersect with other minorities have even less power like women of color and trans individuals [citation]. Women having less power than their male counterparts can have multiple negative outcomes such as continued and sustained sexual aggression, low self-esteem, financial insecurity, lack of freedom of movement, lack of freedom of thought, and in some extreme cases even death [citations]. Cultural relativism creates a difficulty in cultures that have opposing views on the rights and how to navigate that can in and of itself reflect institutional power imbalances.

Power imbalances can create a dissociative state where those with less power are seen as more of an object than a person [@lammers2011; @gwinn2013; @smith2016; @haslam2014]. While others with more power may see those with less as be less human, some individuals attribute the dehumanization to themselves as well and self-dehumanize [@bastian2010; @bastian2012; @bastian2013; @kouchaki2018]. Effects of prolonged dehumanization by those with more power often, unchecked and under constant pressure, can lead some individuals to believe what the powerholders say is true. The question remains, why do people in power begin to dehumanize those with less power? Commonly when an individual harms another usually there is some perspective taking by the harmer. However, to dehumanize the other person it lessens the sense of empathy that one would normally feel thus allowing for more damage and harm to be committed [citations]. “With great power comes great responsibility” often quoted by Uncle Ben in the Spider-Man comic books, yet has its possible historical foundations in the French National Convention in 1793, leads credence to the wane and flow of the effects of power [@nationaleparis1793]. Those in power make decisions for those for which they are leaders. As is the case with every decision there is a reaction to the decision. Sometimes those effects are negative and those with less power may be harmed in the process. Dehumanization of those in less power acts as a defense mechanism to continue making life changing decisions.

Often dehumanization is left to more extreme occasions such as war, infrahumanization, where ascriptions of nonhuman qualities are more subtle and not as extreme [@haslam2014]. Research in dehumanization/infrahumanization by Gwinn and colleagues used game theory and university students to simulate power differentials [-@gwinn2013]. In their research they found that once individuals began to gain power, they would ascribe fewer humanlike personality traits than those with less power ascribing traits to the powerful. Interestingly, there is a reciprocal relationship between self-dehumanization and immoral behavior [@kouchaki2018]. When individuals would commit an immoral behavior, they would afterwards often feel less human, which in turn has them act more immoral.

## Cognition
When deciding, the decisions are not subject to a vacuum. Every decision that is made is contingent on the prior understanding and knowledge of the situation and the possible outcomes of those decisions. The woman choosing one tie over another or the little boy choosing one doll to play with is contingent on the knowledge that they both separately have gained in their lives so far. It could be said that the time at which an infant is first learning about the world is when individual decisions are made by instinct without gained knowledge. When the infant ages and acquires more memories from the environment, it will begin to use those memories in making future decisions.

The first step at acquiring new knowledge is interacting with the environment. One explanation that has been garnering more cognitive and biological attention is from Dr. Nelson Cowan’s integrated working memory model [@cowan1999]. In the integrated working memory model there are four key areas in attaining new information: [1] a brief sensory store, [2] a long term store, [3] the focus of attention, [4] and the central executive. Each key area has a separate function[s] that allows for new information to be “judged” against the existing information. The information that is then held temporarily in a sensory store to where it is then sent to the long term store to be “directed” by the central executive which is a metacognitive process that controls and directs where attention should be placed on the incoming information. There is then a controlled more conscious action or an automatic action based on the type of incoming information. Information that is automatic usually is considered habituated to the memory system and is therefore not a novel stimulus. More focus is given to information/stimuli that is more novel. In the integrated working memory model information that is incoming in the brain is often “filtered” through a lens that is understandable to the individual, novel stimuli. From here the information is then encoded and stored in long-term memory for reactivation by new stimuli.

The integrated working memory model is similar in thought to how individuals make decisions based on the laws and customs of a society. Johnathan is a normal member of his community. They participate in a common game in the park with some friends. Johnathan says an inappropriate joke to one of their friends. The others overhear and judge, automatically, the content of the joke to the governed norms of the community. Because this joke is outside the common norms of the community, the others see Johnathan as violating their moral code. Johnathan’s friends would then automatically analyze the joke against existing information and attend to the key features. Like how the central executive guides and directs attention to the new novel stimuli, the inappropriate joke. Interesting research has been done with morality and metacognition.

Common to research in metacognition and moral reasoning is theory of mind. A theory of mind is the ability for an individual to attribute or recognize the inner workings of the mind and differentiate those from the self and others [citation]. Research in theory of mind has contributed to our understanding of autism, schizophrenia, and traumatic brain injury [@byom2013]. An individual with deficits of theory of mind would for example be unable to attribute signs of happiness on other people, such as a smile or a frown [citation]. In the case of Johnathan, if they had a theory of mind deficits, they would be unable or have difficulty in noticing the dissatisfaction of their joke. Research using theory of mind to investigate social situations such as the example with Jonathan helps psychologists get a better understanding of how moral judgement works and is affected by deficits in the cognitive system.

As discussed thus far, cognitively, each component contributes and affects the individual in a multitude of ways. As previously discussed in the section on risky sexual behaviors, how the individual sees themselves and how they believe others see them is exceptionally important to their overall cognitive health. These sexual schemas that each of us create about ourselves is influenced by daily interactions and prior history, whether sexual. Outside of how the sexual schema individuals create about themselves affects their later sexual health, it can change how they see and interact with the world around them.

The prior knowledge that individuals have can have a negative effect on their ability to gain and hold new information. Those with lower prior knowledge of a given technology often have difficulty in reconstructing the information of a new product compared to those that have less prior knowledge [Wood & Lynch, 2002]. When people are presented with new information, a new technology, encoding of the new information takes place. As that occurs, prior information of the technology is retrieved, and an inference is made on subsequent information by comparing the new and old information. This affects the ability to encode the new information “correctly” and can disrupt later retrieval of the former. Similar effects are seen when investigating motivational forces. Individuals with prior knowledge may also have an overconfidence of the information that they already have and are not as motivated to attend to the information they are learning.

Extending the research on prior knowledge and new technology, prior knowledge and complacency has also been seen with contracting an STI, a virus, or chances of getting pregnant [citations]. The decisional factors that occur cognitively to choose safe sex practices is complex and subject to frequent change. Many people that are confronted with decisions, such as the mundane choice of what shoes to wear, base their decisions from using a variety of cognitive methods. Often, the choice to wear a condom or other safe sex practices is through a risk heuristic of contracting or transmitting a sexually transmitted infection. With decisions based on issues of purity, such as sex, one heuristic that is commonly employed is the affect heuristic. The affect heuristic in judgements of risk is where the thought or priming of a specific word triggers a quick emotional response to that stimuli word [@finucane2000]. When presented with words that are physically harmful such as cigarettes or pesticides, participants rated the words as too risky and reported negative feelings concerning those stimulus words. Affective considerations of high-risk situations are often put into perspective with individuals in risky situations.

An artifact of how issues such as HIV, Human Immunodeficiency Virus, discussed in the media and the community that it affects creates a cognitive problem with individuals judging the likelihood of catching the virus, especially women. In the media it is often discussed how men who have sex with men are the main individuals catching and spreading HIV. While HIV still affects the LGBTQ+ community, the discussion around susceptibility affects other individuals outside of the LGBTQ+ community negatively as well. Women, for example, have a genetically higher susceptibility to the virus [citation]. That being so, often due to unintended ignorance to their chances are one of the leading groups contracting new cases of HIV [citation]. Downlow culture as well increases the chances of contracting the virus. Amongst some men that do not wish to acknowledge their own homosexuality will choose to forgo the condom, implies a premeditation, and do not necessarily believe they will contract the virus [citation]. Both examples are contributed by the representation of HIV in the media and the current zeitgeist.

Common in all decisions is the difficulty and uncomfortability between different decisions and opposing situations, is cognitive dissonance [@festinger1957]. An interesting cognitive dissonant series of thoughts that some males have is when choosing to wear a condom. Often, there will be the cognition of not wanting to contract an STI, but also believing that condoms are uncomfortable [@macphail2001]. In addition to believing they are uncomfortable there is an interesting cultural belief amongst some young men that wearing a condom makes them less of a man [@vincent2016; @pleck1993]. To some the main decisional factor in whether to wear a condom is not contracting an STI or getting pregnant [citation]. While, as noted with perceptions on condoms, often comfort and how others will see them is the main factor. Sexually active or those thinking to become sexually active often get their opinions on sexual activity and safety practices from their peers. Often, the opinions of peers are more influential than those of the parent[s]. Interestingly, some men believe that due to the cultural cognition around contraception, discussions and decisions of contraception is a female decision [@castrovazquez2000].

### Aggression and Cognition
Connected to spitefulness, moral judgment, and cognition is human aggression. Traditionally, aggression is differentiated between the outcome or motivation of the incident. Aggression as it is operationally defined is behavior that is committed by the actor to another with the intent to harm the other [@anderson2002]. This is then further differentiated to violence where violence is the intent to cause severe harm such as death. From aggression research and moral judgment, cognitive neoassociation theory [CNT] was beginning to become tantamount in research on aggressive behavior.

In CNT, similar to the study of disgust association where some research suggests that inducing the disgust response to smell causes individuals to become more conservative against breaking moral norms [@tybur2009; @eskine2011; @horberg2009; @laakasuo2017]. Important to the present discussion on sexual judgment, research by Laakasuo and colleagues suggest that disgust is only predictive of sexual disgust [-@laakasuo2017]. From CNT, Anderson and Bushman developed the General Aggression Model [GAM] is a theoretical outline that combines multiple smaller domain specific theories on aggression like CNT [-@anderson2002]. The GAM has processes: inputs, routes, and outcomes of a social situation. The inputs separate into a person and situation centered inputs. The individual then has an internal examination of the person or situation, cognitions like affective processes, availability heuristics, theory of mind evaluations, scripts and schemata [@barnett2013; @kahneman1972; scripts and schemata citation]. Appraisal and a decision process are the last step in the GAM, where the individual evaluates the situation based on the inputs and routes. Anderson and Bushman contend that there are two types of outcomes, thoughtful and impulsive actions. Like the affective heuristic, the impulsive action is often fast and does not require as much deliberation. While the thoughtful action requires more time and evaluation of all the possible outcomes.

Scripts and schemata are key components of the GAM. Schema, more broadly than sexual schema, are cognitive compositions or structures that represent objects or ideas interconnected by their features [@dimaggio1997]. Multiple representations of schema and stereotypical event sequences are labelled as scripts [@abelson1981]. A classic example of a cognitive script is events surrounding reading the menu at a restaurant [@abelson1981]. An individual is at a restaurant and needs to order from the menu. However, they lost their reading glasses. As Abelson contends, the reader must infer what is needed in reading a menu, what occurs at a restaurant, and so on. The automatic process of schematic activation begins with certain key features of an object or event being noticed by the individual. For example, recognizing a tree one of the first features that are noticed that distinguishes a tree are the leaves. From the leaves, the bark is activated, and so on making up the concept of a tree.

Often aggression and discrimination can be understood through the schematic model. Media and social representations of individuals, especially men of color, have often made assumptions and portrayed them as violent and criminals. Currently a majority of US adults in a recent Pew Research Center poll report that race relations are currently worse, Black Americans and people of color in general report more cases of discrimination, and a majority say Black Americans in particular are treated unfairly by the police [@pewresearchcenter2019]. Aggression or discrimination is often the result of associating one group with negative connotations. For example, in the case of those that believe Black Americans are criminals they have through cognitive associations have related the schematic concept of criminal with the features/schema of what they believe is a Black American. The discrimination and aggression then occur through the GAM processes with negative actions being the outcome.

Pertinent after the advent of the me-too movement, see section 3, issues of how these power over views of women, especially women of color and trans women of color, become learned and develop in sexual aggression. Sexual aggression in and of itself is a subgroup of aggression where the intent to harm is sexual in nature [@anderson2002; @malamuth1995]. Many of the targets of sexual aggression are women of color and trans women of color [citations]. In the reported cases men are often the perpetrators of the crimes [@anderson2002]. The aggression itself appears to be domain specific to one gender, women. Often, acts of sexual aggression are verbal in nature, such as asking repeatedly for sex or threatening to break up with them [@testa2015]. When individuals gain power they may aggress more over those that have less power, which may pay head to the continued sexual aggression and sexual violence against women of color and trans women of color for whom have historically low levels of power [citations].

Recent research by Garnett and Mann investigate the cognitive and empathetical processes of those that commit a sexual aggression or sexual violence, labelled as sexual offending [-@barnett2013]. Common to research on sexual offenses, research contends that those that do offend do so with a lack of empathy towards their victims [@hudson1993]. As noted in the previous section on moral judgment, see section 3, empathetic processing by these offenders are more complex than the simple inability to “feel” or identify the emotions of others. There is a recurring theme amongst offenders of women being deceitful and sexually entitled [@barnett2013; @gannon2009]. The offenders often feel slighted when a woman denies their sexual advances which then tends to lead to some sexual aggression [@williams2017; @gannon2009].

The rejection of the sexual advances of the man often damage their sense of masculinity [@malamuth1996]. Relating back to beliefs on condom use amongst men, even the request of wearing condom could be interpreted as damaging their sense of masculinity [@castrovazquez2000]. If the woman, in a heterosexual relationship, brings the condom they are damaging the males masculinity but if the male brings the condom he could also be considered a thoughtful individual. While the woman would be seen as easy. This could then lead to bullying behavior and ostracization from the moral judgment of the community on the woman’s purity, see section moral judgment.
\newpage