---
title: "R-analysis_cleaning"
author: "Andrew Ithurburn"
date: "01/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r bayesian correlation, message=FALSE, warning=FALSE}
library(brms)
library(rstan)
 # can remove the unnecessary iterations
corrs <- brm(mvbind(ethicalPreference, financialPreference, socialPreference, healthAndSafetyPreference, recreationalPreference) ~ 1, data = experiment_dataset_analysis, family = student, prior = c(prior(gamma(2, .1), class = "nu"), prior(normal(0, 1), class = "Intercept"), prior(normal(0, 1), class = "sigma", resp = "ethicalPreference"), prior(normal(0, 1), class = "sigma", resp = "financialPreference"), prior(normal(0, 1), class = "sigma", resp = "healthAndSafetyPreference"), prior(normal(0, 1), class = "sigma", resp = "recreationalPreference"), prior(normal(0, 1), class = "sigma", resp = "socialPreference")), iter = 2000, warmup = 500)

summary(corrs)
plot(corrs)
```


```{r main analysis}

experiment_dataset_analysis <- subset(experiment_dataset_analysis, experiment_dataset_analysis$Gender != "2")

m1 <- brm(generalRiskPreference ~ dominanceSum + prestigeSum + leadershipSum + Gender + Age, data = experiment_dataset_analysis, 
           prior = c(prior(normal(0, 1), class = "Intercept"),
                     prior(normal(3, 1), class = "b", coef = "dominanceSum"),
                     prior(normal(0, 1), class = "b", coef = "prestigeSum"), 
                     prior(normal(-2, 1), class = "b", coef = "leadershipSum"),
                     prior(normal(-3, 1), class = "b", coef = "Gender1"), 
                     prior(normal(-3, 1), class = "b", coef = "Age")), save_all_pars = T, iter = 4000)

summary(m1)

h1 <- hypothesis(m1, "dominanceSum > prestigeSum" )
h1
library(bayestestR)
m1_hdi <- hdi(m1, effects = "fixed", component = "conditional", ci = .95)

m1_hdi[sign(m1_hdi$CI_low) == sign(m1_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
```

```{r}

# interaction between gender and each of the DoPL motives
m1_int <- brm(generalRiskPreference ~ dominanceSum*Gender+ prestigeSum*Gender + leadershipSum*Gender + Age, data=experiment_dataset_analysis,
              prior=c(prior(normal(0,1), class="Intercept"),
                      prior(normal(3,1), class="b", coef="dominanceSum"),
                      prior(normal(0,1), class="b", coef="prestigeSum"),
                      prior(normal(-2,1), class="b", coef="leadershipSum"),
                      prior(normal(-3,1), class="b", coef="Gender1"),
                      prior(normal(-3,1), class="b", coef="Age"),
                      prior(normal(0,1), class="b", coef="dominanceSum:Gender1"),
                      prior(normal(0,1), class="b", coef="Gender1:leadershipSum"),
                      prior(normal(0,1), class="b", coef="Gender1:prestigeSum")), 
              save_all_pars = T, iter = 4000, warmup = 500)
summary(m1_int)

# hdi intervals interaction model
m1_int_hdi <- hdi(m1_int, effects = "fixed", component = "conditional", ci = .95)
m1_int_hdi[sign(m1_int_hdi$CI_low) == sign(m1_int_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
```

```{r}

# Interaction between gender and dominance
m1_int_d <- brm(generalRiskPreference ~ dominanceSum*Gender+ prestigeSum + leadershipSum + Age, data =experiment_dataset_analysis,
              prior=c(prior(normal(0,1), class="Intercept"),
                      prior(normal(3,1), class="b", coef="dominanceSum"),
                      prior(normal(0,1), class="b", coef="prestigeSum"),
                      prior(normal(-2,1), class="b", coef="leadershipSum"),
                      prior(normal(-3,1), class="b", coef="Gender1"),
                      prior(normal(-3,1), class="b", coef="Age"),
                      prior(normal(0,1), class="b", coef="dominanceSum:Gender1")), 
              save_all_pars = T, iter = 4000, warmup = 500)

summary(m1_int_d)

# HDI
m1_int_d_hdi <- hdi(m1_int_d, effects = "fixed", component = "conditional", ci = .95)
m1_int_d_hdi[sign(m1_int_d_hdi$CI_low) == sign(m1_int_d_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
```

```{r}

# Interaction between gender and leadership
m1_int_l <- brm(generalRiskPreference ~ dominanceSum + prestigeSum + leadershipSum*Gender + Age, data=experiment_dataset_analysis,
              prior=c(prior(normal(0,1), class="Intercept"),
                      prior(normal(3,1), class="b", coef="dominanceSum"),
                      prior(normal(0,1), class="b", coef="prestigeSum"),
                      prior(normal(-2,1), class="b", coef="leadershipSum"),
                      prior(normal(-3,1), class="b", coef="Gender1"),
                      prior(normal(-3,1), class="b", coef="Age"),
                      prior(normal(0,1), class="b", coef="leadershipSum:Gender1")), 
              save_all_pars = T, iter = 4000, warmup = 500)

summary(m1_int_l)

# HDI 
m1_int_l_hdi <- hdi(m1_int_l, effects = "fixed", component = "conditional", ci = .95)
m1_int_l_hdi[sign(m1_int_l_hdi$CI_low) == sign(m1_int_l_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
```

```{r}            
            
# Interaction between gender and prestige
m1_int_p <- brm(generalRiskPreference ~ dominanceSum+ prestigeSum*Gender + leadershipSum + Age, data=experiment_dataset_analysis,
              prior=c(prior(normal(0,1), class="Intercept"),
                      prior(normal(3,1), class="b", coef="dominanceSum"),
                      prior(normal(0,1), class="b", coef="prestigeSum"),
                      prior(normal(-2,1), class="b", coef="leadershipSum"),
                      prior(normal(-3,1), class="b", coef="Gender1"),
                      prior(normal(-3,1), class="b", coef="Age"),
                      prior(normal(0,1), class="b", coef="prestigeSum:Gender1")), 
              save_all_pars = T, iter = 4000)

summary(m1_int_p)

# HDI
m1_int_p_hdi <- hdi(m1_int_p, effects = "fixed", component = "conditional", ci = .95)
m1_int_p_hdi[sign(m1_int_p_hdi$CI_low) == sign(m1_int_p_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
```

```{r}

# Domain specific model
m2 <- brm(mvbind(ethicalPreference, financialPreference, socialPreference, healthAndSafetyPreference, recreationalPreference) ~ dominanceSum + prestigeSum + leadershipSum + Gender + Age, data = experiment_dataset_analysis, cores = 6
    prior = c(prior(normal(0, 1),  coef = "Age", resp = "ethicalPreference"),
              prior(normal(0, 1),  coef = "Gender1", resp = "ethicalPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "ethicalPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "ethicalPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "ethicalPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "ethicalPreference"), 
              prior(normal(0, 1), class = "sigma", resp = "ethicalPreference"), 
              #----
              prior(normal(0, 1),  coef = "Age", resp = "financialPreference"),
              prior(normal(0, 1),  coef = "Gender1", resp = "financialPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "financialPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "financialPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "financialPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "financialPreference"),
              prior(normal(0, 1), class = "sigma", resp = "financialPreference"), 
              #----
              prior(normal(0, 1),  coef = "Age", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1),  coef = "Gender1", resp = "healthAndSafetyPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class = "sigma", resp = "healthAndSafetyPreference"),
              #----
              prior(normal(0, 1),  coef = "Age", resp = "recreationalPreference"),
              prior(normal(0, 1),  coef = "Gender1", resp = "recreationalPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "recreationalPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "recreationalPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "recreationalPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "recreationalPreference"),
              prior(normal(0, 1), class = "sigma", resp = "recreationalPreference"), 
              #----
              prior(normal(0, 1),  coef = "Age", resp = "socialPreference"),
              prior(normal(0, 1),  coef = "Gender1", resp = "socialPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "socialPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "socialPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "socialPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "socialPreference"), 
              prior(normal(0, 1), class = "sigma", resp = "socialPreference")), 
              save_all_pars = T, iter = 6000, warmup = 500) 


summary(m2)

m2_hdi <- hdi(m2, effects = "fixed", component = "conditional", ci = .95)
m2_hdi[sign(m2_hdi$CI_low) == sign(m2_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
```

```{r}            
            
 # Domain specific model with Gender-DOPL interactions
m3 <- brm(mvbind(ethicalPreference, financialPreference, socialPreference, healthAndSafetyPreference, recreationalPreference) ~ dominanceSum*Gender + prestigeSum*Gender + leadershipSum*Gender + Age, data = experiment_dataset_analysis, cores = 6,
              prior = c(prior(normal(0, 1),  coef = "Age", resp = "ethicalPreference"),
              prior(normal(0, 1),  coef = "Gender1", resp = "ethicalPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "ethicalPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "ethicalPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "ethicalPreference"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "ethicalPreference"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "ethicalPreference"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "ethicalPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "ethicalPreference"), 
              prior(normal(0, 1), class = "sigma", resp = "ethicalPreference"), 
              #----
              prior(normal(0, 1),  coef = "Age", resp = "financialPreference"),
              prior(normal(0, 1),  coef = "Gender1", resp = "financialPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "financialPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "financialPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "financialPreference"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "financialPreference"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "financialPreference"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "financialPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "financialPreference"),
              prior(normal(0, 1), class = "sigma", resp = "financialPreference"), 
              #----
              prior(normal(0, 1),  coef = "Age", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1),  coef = "Gender1", resp = "healthAndSafetyPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class = "sigma", resp = "healthAndSafetyPreference"), 
              #----
              prior(normal(0, 1),  coef = "Age", resp = "recreationalPreference"),
              prior(normal(0, 1),  coef = "Gender1", resp = "recreationalPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "recreationalPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "recreationalPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "recreationalPreference"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "recreationalPreference"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "recreationalPreference"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "recreationalPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "recreationalPreference"),
              prior(normal(0, 1), class = "sigma", resp = "recreationalPreference"),
              #----
              prior(normal(0, 1),  coef = "Age", resp = "socialPreference"),
              prior(normal(0, 1),  coef = "Gender1", resp = "socialPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "socialPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "socialPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "socialPreference"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "socialPreference"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "socialPreference"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "socialPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "socialPreference"), 
              prior(normal(0, 1), class = "sigma", resp = "socialPreference")), 
save_all_pars = T, iter = 6000, warmup = 500) 

summary(m3)

# HDI
m3_hdi <- hdi(m3, effects = "fixed", component = "conditional", ci = .95)
m3_hdi[sign(m3_hdi$CI_low) == sign(m3_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
            
# Model Comparison (m2 and m3)
co <- loo(m2,m3)

looic_ <- c(co$loos$m2$looic, co$loos$m3$looic)
looic_se <- c(co$loos$m2$se_looic, co$loos$m3$se_looic)
looic_elpd <- c(co$loos$m2$elpd_loo, co$loos$m3$elpd_loo)
looic_elpd_se <- c(co$loos$m2$se_elpd_loo, co$loos$m3$se_elpd_loo)

loo_table <- data.frame(looic, looic_se, looic_elpd,looic_elpd_se, row.names = c("m2", "m3"))
loo_table

bayes_R2(m2)
bayes_R2(m3)

```

```{r}
m6 <- brm(mvbind(ethicalPreference, financialPreference, socialPreference, healthAndSafetyPreference, recreationalPreference) ~ dominanceSum*Age + prestigeSum*Age + leadershipSum*Age + Age, data = experiment_dataset_analysis, cores = 6,
              prior = c(prior(normal(0, 1),  coef = "Age", resp = "ethicalPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "ethicalPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "ethicalPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "ethicalPreference"),
              prior(normal(0, 1), coef = "dominanceSum:Age", resp = "ethicalPreference"),
              prior(normal(0, 1), coef = "Age:prestigeSum", resp = "ethicalPreference"),
              prior(normal(0, 1), coef = "Age:leadershipSum", resp = "ethicalPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "ethicalPreference"), 
              prior(normal(0, 1), class = "sigma", resp = "ethicalPreference"), 
              #----
              prior(normal(0, 1),  coef = "Age", resp = "financialPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "financialPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "financialPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "financialPreference"),
              prior(normal(0, 1), coef = "dominanceSum:Age", resp = "financialPreference"),
              prior(normal(0, 1), coef = "Age:prestigeSum", resp = "financialPreference"),
              prior(normal(0, 1), coef = "Age:leadershipSum", resp = "financialPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "financialPreference"),
              prior(normal(0, 1), class = "sigma", resp = "financialPreference"), 
              #----
              prior(normal(0, 1),  coef = "Age", resp = "healthAndSafetyPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), coef = "dominanceSum:Age", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), coef = "Age:prestigeSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), coef = "Age:leadershipSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class = "sigma", resp = "healthAndSafetyPreference"), 
              #----
              prior(normal(0, 1),  coef = "Age", resp = "recreationalPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "recreationalPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "recreationalPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "recreationalPreference"),
              prior(normal(0, 1), coef = "dominanceSum:Age", resp = "recreationalPreference"),
              prior(normal(0, 1), coef = "Age:prestigeSum", resp = "recreationalPreference"),
              prior(normal(0, 1), coef = "Age:leadershipSum", resp = "recreationalPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "recreationalPreference"),
              prior(normal(0, 1), class = "sigma", resp = "recreationalPreference"),
              #----
              prior(normal(0, 1),  coef = "Age", resp = "socialPreference"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "socialPreference"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "socialPreference"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "socialPreference"),
              prior(normal(0, 1), coef = "dominanceSum:Age", resp = "socialPreference"),
              prior(normal(0, 1), coef = "Age:prestigeSum", resp = "socialPreference"),
              prior(normal(0, 1), coef = "Age:leadershipSum", resp = "socialPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "socialPreference"), 
              prior(normal(0, 1), class = "sigma", resp = "socialPreference")), 
save_all_pars = T, iter = 6000, warmup = 500) 

summary(m6)

# HDI
m6_hdi <- hdi(m6, effects = "fixed", component = "conditional", ci = .95)
m6_hdi[sign(m6_hdi$CI_low) == sign(m6_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
```


```{r}
# Benefit, perception and risk taking across subdomains for DOPL motives
m4 <-  brm(mvbind(riskSum, riskPerceptionSum, riskBenefitSum) ~ dominanceSum + prestigeSum + leadershipSum + Age + Gender, data= experiment_dataset_analysis,
          prior = c(prior(normal(0, 1), class = "Intercept", resp = "riskSum"), 
              prior(normal(0, 1), class = "sigma", resp = "riskSum"), 
              prior(normal(-3, 1),  coef = "Age", resp = "riskSum"),
              prior(normal(-3, 1),  coef = "Gender1", resp = "riskSum"),
              prior(normal(3, 1),  coef = "dominanceSum", resp = "riskSum"),
              prior(normal(-2, 1),  coef = "leadershipSum", resp = "riskSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "riskSum"),
              #----
              prior(normal(0, 1), class = "Intercept", resp = "riskPerceptionSum"),
              prior(normal(0, 1), class = "sigma", resp = "riskPerceptionSum"), 
              prior(normal(3, 1),  coef = "Age", resp = "riskPerceptionSum"),
              prior(normal(3, 1),  coef = "Gender1", resp = "riskPerceptionSum"),
              prior(normal(-3, 1),  coef = "dominanceSum", resp = "riskPerceptionSum"),
              prior(normal(2, 1),  coef = "leadershipSum", resp = "riskPerceptionSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "riskPerceptionSum"),
              #----
              prior(normal(0, 1), class = "Intercept", resp = "riskBenefitSum"),
              prior(normal(0, 1), class = "sigma", resp = "riskBenefitSum"),
              prior(normal(-3, 1),  coef = "Age", resp = "riskBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1", resp = "riskBenefitSum"),
              prior(normal(3, 1),  coef = "dominanceSum", resp = "riskBenefitSum"),
              prior(normal(-2, 1),  coef = "leadershipSum", resp = "riskBenefitSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "riskBenefitSum")), save_all_pars = T, iter = 6500, cores = 6, warmup = 500)
              
summary(m4) 

# HDI
m4_hdi <- hdi(m4, effects = "fixed", component = "conditional", ci = .95)
m4_hdi[sign(m4_hdi$CI_low) == sign(m4_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
   
```

```{r}
     
# Benefit, perception and risk taking across subdomains for DOPL motives and interactions
m5 <-  brm(mvbind(riskSum, riskPerceptionSum, riskBenefitSum) ~ dominanceSum*Gender + prestigeSum*Gender + leadershipSum*Gender + Age, data= experiment_dataset_analysis, iter = 6000, cores = 6, warmup = 500, 
          prior = c(prior(normal(0, 1), class = "Intercept", resp = "riskSum"), 
              prior(normal(0, 1), class = "sigma", resp = "riskSum"), 
              prior(normal(-3, 1), coef = "Age", resp = "riskSum"),
              prior(normal(-3, 1), coef = "Gender1", resp = "riskSum"),
              prior(normal(3, 1), coef = "dominanceSum", resp = "riskSum"),
              prior(normal(-2, 1), coef = "leadershipSum", resp = "riskSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "riskSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "riskSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "riskSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "riskSum"),
              #----
              prior(normal(0, 1), class = "Intercept", resp = "riskPerceptionSum"),
              prior(normal(0, 1), class = "sigma", resp = "riskPerceptionSum"), 
              prior(normal(3, 1), coef = "Age", resp = "riskPerceptionSum"),
              prior(normal(3, 1), coef = "Gender1", resp = "riskPerceptionSum"),
              prior(normal(-3, 1), coef = "dominanceSum", resp = "riskPerceptionSum"),
              prior(normal(2, 1), coef = "leadershipSum", resp = "riskPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "riskPerceptionSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "riskPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "riskPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "riskPerceptionSum"),
              #----
              prior(normal(0, 1), class = "Intercept", resp = "riskBenefitSum"),
              prior(normal(0, 1), class = "sigma", resp = "riskBenefitSum"),
              prior(normal(-3, 1), coef = "Age", resp = "riskBenefitSum"),
              prior(normal(-3, 1), coef = "Gender1", resp = "riskBenefitSum"),
              prior(normal(3, 1), coef = "dominanceSum", resp = "riskBenefitSum"),
              prior(normal(-2, 1), coef = "leadershipSum", resp = "riskBenefitSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "riskBenefitSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "riskBenefitSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "riskBenefitSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "riskBenefitSum")), save_all_pars = T)

summary(m5) 

# HDI
m5_hdi <- hdi(m5, effects = "fixed", component = "conditional", ci = .95)
m5_hdi[sign(m5_hdi$CI_low) == sign(m5_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]

# checking interaction slopes
plot(conditional_effects(m5), points=T)

# Model comparison
co2 <- loo(m4,m5)
co2
comparisonm4 <- loo(m4)
comparisonm5 <- loo(m5)
loocomparison4_5 <- loo_compare(comparisonm4, comparisonm5)
loocomparison4_5

co2$loos$m4$looic
co2$loos$m4$se_looic
co2$loos$m5$looic
co2$loos$m5$se_looic

co2$loos$m4$elpd_loo
co2$loos$m4$se_elpd_loo
co2$loos$m5$elpd_loo
co2$loos$m5$se_elpd_loo

looic_2 <- c(co2$loos$m4$looic, co2$loos$m5$looic)
looic_2_se <- c(co2$loos$m4$se_looic, co2$loos$m5$se_looic)
looic_elpd_2 <- c(co2$loos$m4$elpd_loo, co2$loos$m5$elpd_loo)
looic_elpd_2_se <- c(co2$loos$m4$se_elpd_loo, co2$loos$m5$se_elpd_loo)

loo_table2 <- data.frame(looic_2, looic_2_se, looic_elpd_2,looic_elpd_2_se, row.names = c("m4", "m5"))
loo_table2

bayes_R2(m4)
bayes_R2(m5)

pp_check(m5, resp="riskSum", nsamples = 1000)
pp_check(m5, resp="riskPerceptionSum", nsamples = 1000)
pp_check(m5, resp="riskBenefitSum", nsamples = 1000)
```

```{r}
m7 <-  brm(mvbind(riskSum, riskPerceptionSum, riskBenefitSum) ~ dominanceSum*Age + prestigeSum*Age + leadershipSum*Age + Gender, data= experiment_dataset_analysis, iter = 4000, cores = 6, 
          prior = c(prior(normal(0, 1), class = "Intercept", resp = "riskSum"), 
              prior(normal(0, 1), class = "sigma", resp = "riskSum"), 
              prior(normal(-3, 1), coef = "Age", resp = "riskSum"),
              prior(normal(-3, 1), coef = "Gender1", resp = "riskSum"),
              prior(normal(3, 1), coef = "dominanceSum", resp = "riskSum"),
              prior(normal(-2, 1), coef = "leadershipSum", resp = "riskSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "riskSum"),
              prior(normal(0, 1), coef = "dominanceSum:Age", resp = "riskSum"),
              prior(normal(0, 1), coef = "Age:prestigeSum", resp = "riskSum"),
              prior(normal(0, 1), coef = "Age:leadershipSum", resp = "riskSum"),
              #----
              prior(normal(0, 1), class = "Intercept", resp = "riskPerceptionSum"),
              prior(normal(0, 1), class = "sigma", resp = "riskPerceptionSum"), 
              prior(normal(3, 1), coef = "Age", resp = "riskPerceptionSum"),
              prior(normal(3, 1), coef = "Gender1", resp = "riskPerceptionSum"),
              prior(normal(-3, 1), coef = "dominanceSum", resp = "riskPerceptionSum"),
              prior(normal(2, 1), coef = "leadershipSum", resp = "riskPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "riskPerceptionSum"),
              prior(normal(0, 1), coef = "dominanceSum:Age", resp = "riskPerceptionSum"),
              prior(normal(0, 1), coef = "Age:prestigeSum", resp = "riskPerceptionSum"),
              prior(normal(0, 1), coef = "Age:leadershipSum", resp = "riskPerceptionSum"),
              #----
              prior(normal(0, 1), class = "Intercept", resp = "riskBenefitSum"),
              prior(normal(0, 1), class = "sigma", resp = "riskBenefitSum"),
              prior(normal(-3, 1), coef = "Age", resp = "riskBenefitSum"),
              prior(normal(-3, 1), coef = "Gender1", resp = "riskBenefitSum"),
              prior(normal(3, 1), coef = "dominanceSum", resp = "riskBenefitSum"),
              prior(normal(-2, 1), coef = "leadershipSum", resp = "riskBenefitSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "riskBenefitSum"),
              prior(normal(0, 1), coef = "dominanceSum:Age", resp = "riskBenefitSum"),
              prior(normal(0, 1), coef = "Age:prestigeSum", resp = "riskBenefitSum"),
              prior(normal(0, 1), coef = "Age:leadershipSum", resp = "riskBenefitSum")), save_all_pars = T)

summary(m7) 

# HDI
m7_hdi <- hdi(m7, effects = "fixed", component = "conditional", ci = .95)
m7_hdi[sign(m7_hdi$CI_low) == sign(m7_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
```


```{r}
library(brms)

demo_m1 <- brm(mvbind(dominanceSum, prestigeSum, leadershipSum) ~ Gender + Age + Ethnicity + Education, 
              data = experiment_dataset_analysis, iter = 4000, cores = 6, warmup = 500, 
              prior = c(prior(normal(0,1), class="Intercept"),
                      prior(normal(3,1), coef="Gender1", resp = "dominanceSum"),
                      prior(normal(0,1), coef="Gender1", resp = "leadershipSum"),
                      prior(normal(-2,1), coef="Gender1", resp = "prestigeSum")))
summary(demo_m1)

demo_m1_hdi <- hdi(demo_m1, effects = "fixed", component = "conditional", ci = .95)
demo_m1_hdi[sign(demo_m1_hdi$CI_low) == sign(demo_m1_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]

```

```{r visualization}

experiment_dataset_analysis %>%
  data_grid(generalRiskPreference = seq_range(generalRiskPreference, n = 111)) %>%
  add_predicted_draws(m2) %>%
  ggplot(aes(x = generalRiskPreference, y = dominanceSum)) +
  stat_lineribbon(aes(y = .prediction), .width = c(.99, .95, .8, .5), color = "#08519C") +
  geom_point(data = experiment_1_Dataset, size = 2) +
  scale_fill_brewer()
```

```{r}
priorTest <- c(prior(normal(0, 1), class = "b",resp = "ethicalPreference"),
              prior(normal(0, 1), class = "b", coef = "Age", resp = "ethicalPreference"),
              prior(normal(0, 1), class = "b", coef = "Gender1", resp = "ethicalPreference"),
              prior(normal(2, 1), class = "b", coef = "dominanceSum", resp = "ethicalPreference"),
              prior(normal(0, 1), class = "b", coef = "leadershipSum", resp = "ethicalPreference"),
              prior(normal(0, 1), class = "b", coef = "prestigeSum", resp = "ethicalPreference"),
              prior(normal(0, 1), class= "b", coef = "dominanceSum:Gender1", resp = "ethicalPreference"),
              prior(normal(0, 1), class= "b", coef = "Gender1:prestigeSum", resp = "ethicalPreference"),
              prior(normal(0, 1), class= "b", coef = "Gender1:leadershipSum", resp = "ethicalPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "ethicalPreference"), 
              prior(normal(0, 1), class = "sigma", resp = "ethicalPreference"), 
              prior(normal(0, 1), class = "b",resp = "financialPreference"),
              prior(normal(0, 1), class = "b", coef = "Age", resp = "financialPreference"),
              prior(normal(0, 1), class = "b", coef = "Gender1", resp = "financialPreference"),
              prior(normal(2, 1), class = "b", coef = "dominanceSum", resp = "financialPreference"),
              prior(normal(0, 1), class = "b", coef = "leadershipSum", resp = "financialPreference"),
              prior(normal(0, 1), class = "b", coef = "prestigeSum", resp = "financialPreference"),
              prior(normal(0, 1), class= "b", coef = "dominanceSum:Gender1", resp = "financialPreference"),
              prior(normal(0, 1), class= "b", coef = "Gender1:prestigeSum", resp = "financialPreference"),
              prior(normal(0, 1), class= "b", coef = "Gender1:leadershipSum", resp = "financialPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "financialPreference"),
              prior(normal(0, 1), class = "sigma", resp = "financialPreference"), 
              prior(normal(0, 1), class = "b",resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class = "b", coef = "Age", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class = "b", coef = "Gender1", resp = "healthAndSafetyPreference"),
              prior(normal(2, 1), class = "b", coef = "dominanceSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class = "b", coef = "leadershipSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class = "b", coef = "prestigeSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class= "b", coef = "dominanceSum:Gender1", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class= "b", coef = "Gender1:prestigeSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class= "b", coef = "Gender1:leadershipSum", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "healthAndSafetyPreference"),
              prior(normal(0, 1), class = "sigma", resp = "healthAndSafetyPreference"), 
              prior(normal(0, 1), class = "b",resp = "recreationalPreference"),
              prior(normal(0, 1), class = "b", coef = "Age", resp = "recreationalPreference"),
              prior(normal(0, 1), class = "b", coef = "Gender1", resp = "recreationalPreference"),
              prior(normal(2, 1), class = "b", coef = "dominanceSum", resp = "recreationalPreference"),
              prior(normal(0, 1), class = "b", coef = "leadershipSum", resp = "recreationalPreference"),
              prior(normal(0, 1), class = "b", coef = "prestigeSum", resp = "recreationalPreference"),
              prior(normal(0, 1), class= "b", coef = "dominanceSum:Gender1", resp = "recreationalPreference"),
              prior(normal(0, 1), class= "b", coef = "Gender1:prestigeSum", resp = "recreationalPreference"),
              prior(normal(0, 1), class= "b", coef = "Gender1:leadershipSum", resp = "recreationalPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "recreationalPreference"),
              prior(normal(0, 1), class = "sigma", resp = "recreationalPreference"), 
              prior(normal(0, 1), class = "b",resp = "socialPreference"),
              prior(normal(0, 1), class = "b", coef = "Age", resp = "socialPreference"),
              prior(normal(0, 1), class = "b", coef = "Gender1", resp = "socialPreference"),
              prior(normal(2, 1), class = "b", coef = "dominanceSum", resp = "socialPreference"),
              prior(normal(0, 1), class = "b", coef = "leadershipSum", resp = "socialPreference"),
              prior(normal(0, 1), class = "b", coef = "prestigeSum", resp = "socialPreference"),
              prior(normal(0, 1), class= "b", coef = "dominanceSum:Gender1", resp = "socialPreference"),
              prior(normal(0, 1), class= "b", coef = "Gender1:prestigeSum", resp = "socialPreference"),
              prior(normal(0, 1), class= "b", coef = "Gender1:leadershipSum", resp = "socialPreference"),
              prior(normal(0, 1), class = "Intercept", resp = "socialPreference"), 
              prior(normal(0, 1), class = "sigma", resp = "socialPreference"))

```

```{r m7_DoPL and DOSPERT}
m7_DoPL_DOSPERT <- brm(mvbind(dominanceSum, prestigeSum, leadershipSum) ~ ethicalPreference + financialPreference + socialPreference + healthAndSafetyPreference + recreationalPreference, data = experiment_dataset_analysis,
                       iter = 6500, warmup = 500,
                     prior = c(prior(normal(0, 1), class = "Intercept"),
                               prior(normal(0, 1), class = "sigma", resp = "dominanceSum"),
                               prior(normal(0, 1), class = "sigma", resp = "prestigeSum"),
                               prior(normal(0, 1), class = "sigma", resp = "leadershipSum"),
                               prior(normal(0, 1), coef = "ethicalPreference", resp = "dominanceSum"),
                               prior(normal(0, 1), coef = "financialPreference", resp = "dominanceSum"),
                               prior(normal(0, 1), coef = "healthAndSafetyPreference", resp = "dominanceSum"), 
                               prior(normal(0, 1), coef = "recreationalPreference", resp = "dominanceSum"), 
                               prior(normal(0, 1), coef = "socialPreference", resp = "dominanceSum"),
                               prior(normal(0, 1), coef = "ethicalPreference", resp = "prestigeSum"),
                               prior(normal(0, 1), coef = "financialPreference", resp = "prestigeSum"),
                               prior(normal(0, 1), coef = "healthAndSafetyPreference", resp = "prestigeSum"), 
                               prior(normal(0, 1), coef = "recreationalPreference", resp = "prestigeSum"), 
                               prior(normal(0, 1), coef = "socialPreference", resp = "prestigeSum"),
                               prior(normal(0, 1), coef = "ethicalPreference", resp = "leadershipSum"),
                               prior(normal(0, 1), coef = "financialPreference", resp = "leadershipSum"),
                               prior(normal(0, 1), coef = "healthAndSafetyPreference", resp = "leadershipSum"), 
                               prior(normal(0, 1), coef = "recreationalPreference", resp = "leadershipSum"), 
                               prior(normal(0, 1), coef = "socialPreference", resp = "leadershipSum")),
                               save_all_pars = T)

summary(m7_DoPL_DOSPERT)

```

```{r}

bayes_R2(m1)

```


```{r Perceived risk and age}
m4_perceivedRisk_Age <- brm(mvbind(ethicalQuestionsPerceptionSum, financialQuestionsPerceptionSum, socialQuestionsPerceptionSum, recreationalQuestionsPerceptionSum, healthAndSafetyQuestionsPerceptionSum) ~ dominanceSum*Age + prestigeSum*Age + leadershipSum*Age + Gender + Age, iter = 4000, warmup = 500,
                           data = experiment_dataset_analysis, 
                           prior =  
                          c(prior(normal(0, 1), class = "Intercept",resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Age", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(-3, 1), coef = "Gender1", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(-3, 1), coef = "dominanceSum:Age", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(-2, 1), coef = "Age:leadershipSum", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(-2, 1), coef = "Age:prestigeSum", resp = "ethicalQuestionsPerceptionSum"), 
              #---- Perception of financial risk taking
              prior(normal(0, 1), coef = "Age", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1", resp = "financialQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum:Age", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Age:leadershipSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Age:prestigeSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "Intercept", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "sigma", resp = "financialQuestionsPerceptionSum"),
              #---- Perception of risk in health and safety
              prior(normal(0, 1), coef = "Age", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum:Age", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Age:leadershipSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Age:prestigeSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "Intercept", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "sigma", resp = "healthAndSafetyQuestionsPerceptionSum"),
              #---- Perception of risky recreational settings
              prior(normal(0, 1), coef = "Age", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum:Age", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Age:leadershipSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Age:prestigeSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "Intercept", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "sigma", resp = "recreationalQuestionsPerceptionSum"),
              #---- Perception of social risk
              prior(normal(0, 1), coef = "Age", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1", resp = "socialQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum:Age", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Age:leadershipSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Age:prestigeSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "Intercept", resp = "socialQuestionsPerceptionSum")), 
              save_all_pars = T)

m4_perceivedRisk_Age_hdi <- bayestestR::hdi(m4_perceivedRisk_Age, effects = "fixed", component = "conditional", ci = .95)

m4_perceivedRisk_Age_hdi[sign(m4_perceivedRisk_Age_hdi$CI_low) == sign(m4_perceivedRisk_Age_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
summary(m4_perceivedRisk_Age)
```


```{r Benefit risk and age}

m5_generalRiskPreference <- brm(generalRiskPreference ~ ethicalPreference + socialPreference + financialPreference + healthAndSafetyPreference + recreationalPreference, data = experiment_dataset_analysis,iter = 4000, warmup = 500,
                                prior = c(prior(normal(0, 1), class = "Intercept"),
                               prior(normal(0, 1), coef = "ethicalPreference"),
                               prior(normal(0, 1), coef = "financialPreference"),
                               prior(normal(0, 1), coef = "healthAndSafetyPreference"), 
                               prior(normal(0, 1), coef = "recreationalPreference"), 
                               prior(normal(0, 1), coef = "socialPreference")),
                                          save_all_pars = T)
summary(m5_generalRiskPreference)

m5_benefitRisk_Age <- brm(mvbind(ethicalQuestionsBenefitSum, financialQuestionsBenefitSum, socialQuestionsBenefitSum, recreationalQuestionsBenefitSum, healthAndSafetyQuestionsBenefitSum) ~ dominanceSum*Age + prestigeSum*Age + leadershipSum*Age + Gender + Age, 
                           data = experiment_dataset_analysis, iter = 5000, warmup = 500,
                           prior =  c(prior(normal(0, 1), class = "Intercept", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "Age", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "Gender1", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum:Age", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Age:leadershipSum", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Age:prestigeSum", resp = "ethicalQuestionsBenefitSum"),
              #---- Believed benefit of financial risk 
              prior(normal(0, 1), class = "Intercept", resp = "financialQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "Age", resp = "financialQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1", resp = "financialQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "financialQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "financialQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "financialQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum:Age", resp = "financialQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Age:leadershipSum", resp = "financialQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Age:prestigeSum", resp = "financialQuestionsBenefitSum"),
              #---- Believed benefit of health and safety risk
              prior(normal(0, 1),  coef = "Age", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(3, 1),  coef = "dominanceSum:Age", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Age:leadershipSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Age:prestigeSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(0, 1), class = "Intercept", resp = "healthAndSafetyQuestionsBenefitSum"),
              #---- Believed benefit of recreational risk
              prior(normal(0, 1),  coef = "Age", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum:Age", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Age:leadershipSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Age:prestigeSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(0, 1), class = "Intercept", resp = "recreationalQuestionsBenefitSum"),
              #---- Believed benefit of social risk
              prior(normal(0, 1),  coef = "Age", resp = "socialQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1", resp = "socialQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum:Age", resp = "socialQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Age:leadershipSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Age:prestigeSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(0, 1), class = "Intercept", resp = "socialQuestionsBenefitSum")), 
              save_all_pars = T)

m5_benefitRisk_Age_hdi <- bayestestR::hdi(m5_benefitRisk_Age, effects = "fixed", component = "conditional", ci = .95)

m5_benefitRisk_Age_hdi[sign(m5_benefitRisk_Age_hdi$CI_low) == sign(m5_benefitRisk_Age_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
summary(m5_benefitRisk_Age)
```


```{r}
m4_perceivedRisk_Gender <- brm(mvbind(ethicalQuestionsPerceptionSum, financialQuestionsPerceptionSum, socialQuestionsPerceptionSum, recreationalQuestionsPerceptionSum, healthAndSafetyQuestionsPerceptionSum) ~ dominanceSum*Gender + prestigeSum*Gender + leadershipSum*Gender + Gender + Age, iter = 6000, warmup = 500,
                           data = experiment_dataset_analysis, 
                           prior =  
                          c(prior(normal(0, 1), class = "Intercept",resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Age", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(-3, 1), coef = "Gender1", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(-3, 1), coef = "dominanceSum:Gender1", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(-2, 1), coef = "Gender1:leadershipSum", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(-2, 1), coef = "Gender1:prestigeSum", resp = "ethicalQuestionsPerceptionSum"), 
              #----
              prior(normal(0, 1), coef = "Age", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1", resp = "financialQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum:Gender1", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "Intercept", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "sigma", resp = "financialQuestionsPerceptionSum"),
              #----
              prior(normal(0, 1), coef = "Age", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum:Gender1", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "Intercept", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "sigma", resp = "healthAndSafetyQuestionsPerceptionSum"),
              #----
              prior(normal(0, 1), coef = "Age", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum:Gender1", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "Intercept", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "sigma", resp = "recreationalQuestionsPerceptionSum"),
              #----
              prior(normal(0, 1), coef = "Age", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1", resp = "socialQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "dominanceSum:Gender1", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), class = "Intercept", resp = "socialQuestionsPerceptionSum")), 
              save_all_pars = T)

m4_perceivedRisk_Gender_hdi <- bayestestR::hdi(m4_perceivedRisk_Gender, effects = "fixed", component = "conditional", ci = .95)

m4_perceivedRisk_Gender_hdi[sign(m4_perceivedRisk_Gender_hdi$CI_low) == sign(m4_perceivedRisk_Gender_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
summary(m4_perceivedRisk_Gender)
```


```{r Benefit risk and Gender}

m5_generalRiskPreference <- brm(generalRiskPreference ~ ethicalPreference + socialPreference + financialPreference + healthAndSafetyPreference + recreationalPreference, data = experiment_dataset_analysis,iter = 4000, warmup = 500,
                                prior = c(prior(normal(0, 1), class = "Intercept"),
                               prior(normal(0, 1) ,class = "b", coef = "ethicalPreference"),
                               prior(normal(0, 1) ,class = "b", coef = "financialPreference"),
                               prior(normal(0, 1) ,class = "b", coef = "healthAndSafetyPreference"), 
                               prior(normal(0, 1) ,class = "b", coef = "recreationalPreference"), 
                               prior(normal(0, 1) ,class = "b", coef = "socialPreference")),
                                          save_all_pars = T)
summary(m5_generalRiskPreference)

m5_benefitRisk_Gender <- brm(mvbind(ethicalQuestionsBenefitSum, financialQuestionsBenefitSum, socialQuestionsBenefitSum, recreationalQuestionsBenefitSum, healthAndSafetyQuestionsBenefitSum) ~ dominanceSum*Gender + prestigeSum*Gender + leadershipSum*Gender + Gender + Age, 
                           data = experiment_dataset_analysis, iter = 5000, warmup = 500, cores = 6, 
                           prior =  c(prior(normal(0, 1), class = "Intercept", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "Age", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "Gender1", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum:Gender1", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1:leadershipSum", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1:prestigeSum", resp = "ethicalQuestionsBenefitSum"),
              #----
              prior(normal(0, 1), class = "Intercept", resp = "financialQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "Age", resp = "financialQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1", resp = "financialQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "financialQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "financialQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "financialQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum:Gender1", resp = "financialQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1:leadershipSum", resp = "financialQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1:prestigeSum", resp = "financialQuestionsBenefitSum"),
              #----
              prior(normal(0, 1),  coef = "Age", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(3, 1),  coef = "dominanceSum:Gender1", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1:leadershipSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1:prestigeSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(0, 1), class = "Intercept", resp = "healthAndSafetyQuestionsBenefitSum"),
              #----
              prior(normal(0, 1),  coef = "Age", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum:Gender1", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1:leadershipSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1:prestigeSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(0, 1), class = "Intercept", resp = "recreationalQuestionsBenefitSum"),
              #----
              prior(normal(0, 1),  coef = "Age", resp = "socialQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1", resp = "socialQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "leadershipSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(0, 1),  coef = "prestigeSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(2, 1),  coef = "dominanceSum:Gender1", resp = "socialQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1:leadershipSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(-3, 1),  coef = "Gender1:prestigeSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(0, 1), class = "Intercept", resp = "socialQuestionsBenefitSum")), 
              save_all_pars = T)

m5_benefitRisk_Gender_hdi <- bayestestR::hdi(m5_benefitRisk_Gender, effects = "fixed", component = "conditional", ci = .95)

m5_benefitRisk_Gender_hdi[sign(m5_benefitRisk_Gender_hdi$CI_low) == sign(m5_benefitRisk_Gender_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
summary(m5_benefitRisk_Gender)
```

```{r explorary model}
m8 <- brm(mvbind(ethicalQuestionsRiskSum, ethicalQuestionsPerceptionSum, ethicalQuestionsBenefitSum, 
                 financialQuestionsRiskSum, financialQuestionsPerceptionSum, financialQuestionsBenefitSum,
                 healthAndSafetyQuestionsRiskSum, healthAndSafetyQuestionsPerceptionSum, healthAndSafetyQuestionsBenefitSum,
                 recreationalQuestionsRiskSum, recreationalQuestionsPerceptionSum, recreationalQuestionsBenefitSum,
                 socialQuestionsRiskSum, socialQuestionsPerceptionSum, socialQuestionsBenefitSum) ~ dominanceSum*Gender + prestigeSum*Gender + leadershipSum*Gender + Age, data= experiment_dataset_analysis, iter = 8000, warmup = 500, save_all_pars = T, cores = 6,
          #----
          prior = c(prior(normal(0, 1), class = "Intercept", resp = "ethicalQuestionsRiskSum"), 
              prior(normal(0, 1), class = "sigma", resp = "ethicalQuestionsRiskSum"), 
              prior(normal(-2, 1), coef = "Age", resp = "ethicalQuestionsRiskSum"),
              prior(normal(-2, 1), coef = "Gender1", resp = "ethicalQuestionsRiskSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "ethicalQuestionsRiskSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "ethicalQuestionsRiskSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "ethicalQuestionsRiskSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "ethicalQuestionsRiskSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "ethicalQuestionsRiskSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "ethicalQuestionsRiskSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "ethicalQuestionsPerceptionSum"), 
              prior(normal(0, 1), class = "sigma", resp = "ethicalQuestionsPerceptionSum"), 
              prior(normal(2, 1), coef = "Age", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "Gender1", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(-2, 1), coef = "dominanceSum", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "ethicalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "ethicalQuestionsPerceptionSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "ethicalQuestionsBenefitSum"), 
              prior(normal(0, 1), class = "sigma", resp = "ethicalQuestionsBenefitSum"), 
              prior(normal(-2, 1), coef = "Age", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(-2, 1), coef = "Gender1", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "ethicalQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "ethicalQuestionsBenefitSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "financialQuestionsRiskSum"), 
              prior(normal(0, 1), class = "sigma", resp = "financialQuestionsRiskSum"), 
              prior(normal(-2, 1), coef = "Age", resp = "financialQuestionsRiskSum"),
              prior(normal(-2, 1), coef = "Gender1", resp = "financialQuestionsRiskSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "financialQuestionsRiskSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "financialQuestionsRiskSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "financialQuestionsRiskSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "financialQuestionsRiskSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "financialQuestionsRiskSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "financialQuestionsRiskSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "financialQuestionsPerceptionSum"), 
              prior(normal(0, 1), class = "sigma", resp = "financialQuestionsPerceptionSum"), 
              prior(normal(2, 1), coef = "Age", resp = "financialQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "Gender1", resp = "financialQuestionsPerceptionSum"),
              prior(normal(-2, 1), coef = "dominanceSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "financialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "financialQuestionsPerceptionSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "financialQuestionsBenefitSum"), 
              prior(normal(0, 1), class = "sigma", resp = "financialQuestionsBenefitSum"), 
              prior(normal(-2, 1), coef = "Age", resp = "financialQuestionsBenefitSum"),
              prior(normal(-2, 1), coef = "Gender1", resp = "financialQuestionsBenefitSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "financialQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "financialQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "financialQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "financialQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "financialQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "financialQuestionsBenefitSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "healthAndSafetyQuestionsRiskSum"), 
              prior(normal(0, 1), class = "sigma", resp = "healthAndSafetyQuestionsRiskSum"), 
              prior(normal(-2, 1), coef = "Age", resp = "healthAndSafetyQuestionsRiskSum"),
              prior(normal(-2, 1), coef = "Gender1", resp = "healthAndSafetyQuestionsRiskSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "healthAndSafetyQuestionsRiskSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "healthAndSafetyQuestionsRiskSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "healthAndSafetyQuestionsRiskSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "healthAndSafetyQuestionsRiskSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "healthAndSafetyQuestionsRiskSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "healthAndSafetyQuestionsRiskSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "healthAndSafetyQuestionsPerceptionSum"), 
              prior(normal(0, 1), class = "sigma", resp = "healthAndSafetyQuestionsPerceptionSum"), 
              prior(normal(2, 1), coef = "Age", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "Gender1", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(-2, 1), coef = "dominanceSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "healthAndSafetyQuestionsPerceptionSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "healthAndSafetyQuestionsBenefitSum"), 
              prior(normal(0, 1), class = "sigma", resp = "healthAndSafetyQuestionsBenefitSum"), 
              prior(normal(-2, 1), coef = "Age", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(-2, 1), coef = "Gender1", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "healthAndSafetyQuestionsBenefitSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "recreationalQuestionsRiskSum"), 
              prior(normal(0, 1), class = "sigma", resp = "recreationalQuestionsRiskSum"), 
              prior(normal(-2, 1), coef = "Age", resp = "recreationalQuestionsRiskSum"),
              prior(normal(-2, 1), coef = "Gender1", resp = "recreationalQuestionsRiskSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "recreationalQuestionsRiskSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "recreationalQuestionsRiskSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "recreationalQuestionsRiskSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "recreationalQuestionsRiskSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "recreationalQuestionsRiskSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "recreationalQuestionsRiskSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "recreationalQuestionsPerceptionSum"), 
              prior(normal(0, 1), class = "sigma", resp = "recreationalQuestionsPerceptionSum"), 
              prior(normal(2, 1), coef = "Age", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "Gender1", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(-2, 1), coef = "dominanceSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "recreationalQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "recreationalQuestionsPerceptionSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "recreationalQuestionsBenefitSum"), 
              prior(normal(0, 1), class = "sigma", resp = "recreationalQuestionsBenefitSum"), 
              prior(normal(-2, 1), coef = "Age", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(-2, 1), coef = "Gender1", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "recreationalQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "recreationalQuestionsBenefitSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "socialQuestionsRiskSum"), 
              prior(normal(0, 1), class = "sigma", resp = "socialQuestionsRiskSum"), 
              prior(normal(-2, 1), coef = "Age", resp = "socialQuestionsRiskSum"),
              prior(normal(-2, 1), coef = "Gender1", resp = "socialQuestionsRiskSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "socialQuestionsRiskSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "socialQuestionsRiskSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "socialQuestionsRiskSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "socialQuestionsRiskSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "socialQuestionsRiskSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "socialQuestionsRiskSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "socialQuestionsPerceptionSum"), 
              prior(normal(0, 1), class = "sigma", resp = "socialQuestionsPerceptionSum"), 
              prior(normal(2, 1), coef = "Age", resp = "socialQuestionsPerceptionSum"),
              prior(normal(2, 1), coef = "Gender1", resp = "socialQuestionsPerceptionSum"),
              prior(normal(-2, 1), coef = "dominanceSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "socialQuestionsPerceptionSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "socialQuestionsPerceptionSum"),
              #
              prior(normal(0, 1), class = "Intercept", resp = "socialQuestionsBenefitSum"), 
              prior(normal(0, 1), class = "sigma", resp = "socialQuestionsBenefitSum"), 
              prior(normal(-2, 1), coef = "Age", resp = "socialQuestionsBenefitSum"),
              prior(normal(-2, 1), coef = "Gender1", resp = "socialQuestionsBenefitSum"),
              prior(normal(2, 1), coef = "dominanceSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "leadershipSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "prestigeSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "dominanceSum:Gender1", resp = "socialQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "Gender1:prestigeSum", resp = "socialQuestionsBenefitSum"),
              prior(normal(0, 1), coef = "Gender1:leadershipSum", resp = "socialQuestionsBenefitSum")))
summary(m8)

m8_hdi <- hdi(m8, effects = "fixed", component = "conditional", ci = .95)
m8_hdi[sign(m8_hdi$CI_low) == sign(m8_hdi$CI_high),
            c('Parameter', 'CI','CI_low', 'CI_high')]
```

```{r Visualizations}

mcmc_areas_m1 <- mcmc_areas(m1, pars = c("b_dominanceSum", "b_prestigeSum", "b_leadershipSum", "b_Gender1"))

mcmc_dens_m1 <- mcmc_dens_overlay(m1, pars = c("b_dominanceSum", "b_prestigeSum", "b_leadershipSum", "b_Gender1"))

m1_plot <- mcmc_plot(m1, pars = c("b_dominanceSum", "b_prestigeSum", "b_leadershipSum", "b_Gender1"))

mcmc_areas_m2 <- mcmc_areas(m2, pars = c("b_dominanceSum", "b_prestigeSum", "b_leadershipSum", "b_Gender1"))

mcmc_dens_m2 <- mcmc_dens_overlay(m2, pars = c("b_dominanceSum", "b_prestigeSum", "b_leadershipSum", "b_Gender1"))

m2_plot <- mcmc_plot(m2, pars = c("b_dominanceSum", "b_prestigeSum", "b_leadershipSum", "b_Gender1"))

mcmc_areas_m3 <- mcmc_areas(m3, pars = c("b_dominanceSum", "b_prestigeSum", "b_leadershipSum", "b_Gender1"))

mcmc_dens_m3 <- mcmc_dens_overlay(m3, pars = c("b_dominanceSum", "b_prestigeSum", "b_leadershipSum", "b_Gender1"))

m3_plot <- mcmc_plot(m3, pars = c("b_dominanceSum", "b_prestigeSum", "b_leadershipSum", "b_Gender1"))

mcmc_areas_m4 <- mcmc_areas(m4, pars = c("b_dominanceSum", "b_prestigeSum", "b_leadershipSum", "b_Gender1"))

mcmc_dens_m4 <- mcmc_dens_overlay(m4, pars = c("b_dominanceSum", "b_prestigeSum", "b_leadershipSum", "b_Gender1"))

m4_plot <- mcmc_plot(m4, pars = c("b_dominanceSum", "b_prestigeSum", "b_leadershipSum", "b_Gender1"))
```
