---
title: "R Data tutorial"
author: "Andrew Ithurburn"
date: "22/03/2021"
output:
  word_document: default
  toc: yes
  html_document: null
---

```{r loading the necessary files}
library(DT)
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(papaja)
experiment_1_Dataset <- read.csv("DoPL_DOSPERT.csv", stringsAsFactors = FALSE)

locfunc <- function(data, to){
  which(colnames({{data}})=={{to}})
}
locfunc(experiment_1_Dataset, "DoPL_1")
lfunc <- function(dataset, to, from) {
  loc1 <- which(colnames({{dataset}}) == {{to}})
  loc2 <- which(colnames({{dataset}}) == {{from}})
  length({{dataset}}[loc1:loc2])
}
theme_set(theme_apa(base_size = 12))



```

```{r Look at the data}

datatable(experiment_1_Dataset)

```


```{r}

experiment_1_Dataset <- experiment_1_Dataset[-1:-2,]
```

```{r Look again at the data}

datatable(experiment_1_Dataset)

```


```{r rename the demographic columns, include=FALSE}
colnames(experiment_1_Dataset)[colnames(experiment_1_Dataset) == "Q1"] <- "Gender"
colnames(experiment_1_Dataset)[colnames(experiment_1_Dataset) == "Q78"] <- "Age"
colnames(experiment_1_Dataset)[colnames(experiment_1_Dataset) == "Q35"] <- "Occupation"
colnames(experiment_1_Dataset)[colnames(experiment_1_Dataset) == "Q49"] <- "Education"
colnames(experiment_1_Dataset)[colnames(experiment_1_Dataset) == "Q50"] <- "Ethnicity"


```

```{r locate the the necessary columns and rename to the corresponding datatype}

varname <- "risk"
varname2 <- "riskPerception"
varname3 <- "riskBenefit"



n <- lfunc(experiment_1_Dataset,"Q55_1", "Yes.Q57_10")
n2 <- lfunc(experiment_1_Dataset, "Yes.Q65_1", "Q62_10")
n3 <- lfunc(experiment_1_Dataset, "Q67_1", "Q70_10")


names(experiment_1_Dataset)[locfunc(experiment_1_Dataset, "Q55_1"):locfunc(experiment_1_Dataset, "Yes.Q57_10")] <- unlist(mapply(function(x,y) paste(x, seq(1,y), sep="_"), varname, n))
names(experiment_1_Dataset)[locfunc(experiment_1_Dataset, "Yes.Q65_1"):locfunc(experiment_1_Dataset, "Q62_10")] <- unlist(mapply(function(x,y) paste(x, seq(1,y), sep="_"), varname2, n2))
names(experiment_1_Dataset)[locfunc(experiment_1_Dataset, "Q67_1"):locfunc(experiment_1_Dataset, "Q70_10")] <- unlist(mapply(function(x,y) paste(x, seq(1,y), sep="_"), varname3, n3))

```

```{r begin the recoding process}

experiment_1_Dataset <- experiment_1_Dataset %>%
  mutate_at(vars(locfunc(experiment_1_Dataset, "Gender")), ~as.numeric(recode(.,"Male" = 0, "Female" = 1, "Gender Non-Binary" = 2))) %>%
  mutate_at(vars(locfunc(experiment_1_Dataset, "Education")), ~as.numeric(recode(., "Prefer not to say" = 0, "Primary School" = 1, "GCSEs or equivalent" = 2, "A-levels or equivalent" = 3, "University Undergraduate Program" = 4, "University Postgraduate Program" = 5, "Doctoral Degree" = 6))) %>%
   mutate_at(vars(locfunc(experiment_1_Dataset, 'Ethnicity')), ~as.numeric(recode(., "Prefer not to respond" = 0, "Scottish" = 1, "English" = 2, "European" = 3, "Latin American" = 4, "Asian" = 5, "Arab" = 6, "African" = 7, "Other" = 8))) %>%
   mutate_at(vars(locfunc(experiment_1_Dataset, "risk_1"):locfunc(experiment_1_Dataset, "risk_40")), ~as.numeric(recode(., "Very unlikely" = 1, "Unlikely" = 2, "Not sure" = 3, "Likely" = 4, "Very likely" = 5))) %>%
  mutate_at(vars(locfunc(experiment_1_Dataset, "riskPerception_1"):locfunc(experiment_1_Dataset, "riskPerception_40")), ~as.numeric(recode(., "Not at all risky" = 1, "Somewhat risky" = 2, "Moderately risky" = 3, "Very risky" = 4, "Extremely risky" = 5))) %>%
  mutate_at(vars(locfunc(experiment_1_Dataset, "riskBenefit_1"):locfunc(experiment_1_Dataset, "riskBenefit_40")), ~as.numeric(recode(., "No benefits at all" = 1, "Few benefits" = 2, "Moderate benefits" = 3, "Many benefits" = 4, "Great benefits" = 5))) %>%
  mutate_at(vars(locfunc(experiment_1_Dataset, "DoPL_1"):locfunc(experiment_1_Dataset, "DoPL_5")), ~as.numeric(recode(., "Strongly disagree" = 1, "Disagree" = 2, "Somewhat disagree" = 3, "Somewhat agree" = 4, "Agree" = 5, "Strongly agree" = 6)))  %>%
  mutate_at(vars(locfunc(experiment_1_Dataset, "DoPL_6"), locfunc(experiment_1_Dataset, "DoPL_14")), ~as.numeric(recode(., "Strongly disagree" = 6, "Disagree" = 5, "Somewhat disagree" = 4, "Somewhat agree" = 3, "Agree" = 2, "Strongly agree" = 1))) %>%
  mutate_at(vars(locfunc(experiment_1_Dataset, "DoPL_7"):locfunc(experiment_1_Dataset, "DoPL_13")), ~as.numeric(recode(., "Strongly disagree" = 1, "Disagree" = 2, "Somewhat disagree" = 3, "Somewhat agree" = 4, "Agree" = 5, "Strongly agree" = 6))) %>%
  mutate_at(vars(locfunc(experiment_1_Dataset, "DoPL_15"):locfunc(experiment_1_Dataset, "UMS_10")), ~as.numeric(recode(., "Strongly disagree" = 1, "Disagree" = 2, "Somewhat disagree" = 3, "Somewhat agree" = 4, "Agree" = 5, "Strongly agree" = 6))) %>%
  mutate_at(vars(locfunc(experiment_1_Dataset, "DoPL_17"):locfunc(experiment_1_Dataset, "DoPL_18")), ~as.numeric(recode(., "Not Important To Me" = 1, "Of Little Importance To me" = 2, "Of Some Importance To Me" = 3, "Important To Me" = 4, "Very Important To me" = 5, "Extremely Important To Me" = 6))) %>%
  mutate_at(vars(locfunc(experiment_1_Dataset, "UMS_11"):locfunc(experiment_1_Dataset, "UMS_13")), ~as.numeric(recode(., "Not Important To Me" = 1, "Of Little Importance To me" = 2, "Of Some Importance To Me" = 3, "Important To Me" = 4, "Very Important To me" = 5, "Extremely Important To Me" = 6)))


```

```{r Once recoded remove the unnecessary columns}

```

```{r For ease of analysis store the like columns to their corresponding question type}

```

```{r It would be good to get the sums of the some of the data}



```

```{r Create more like variables with agregate columns}

```

```{r}

datatable(experiment_1_Dataset)

```

